/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-°ËÔÂ-2006 13:07:56
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ekernel.db.or.ORManager;
import com.ekernel.db.or.ORTable;
import com.ttsoft.bjtax.shenbao.model.domain.CZUTDJBXX;
public class CZUTDJBXXTBL extends ORTable {
	static final String tabName = "SFDB.SF_JL_CZUTDJBXX";
	public CZUTDJBXXTBL(ORManager manager) {
		super(manager, tabName, CZUTDJBXX.class);

	}

}
