/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 29-°ËÔÂ-2003 19:40:15
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Czzsnbtzzsj;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class CzzsnbqysjTbl extends ORTable {
	static final String tabName = "SBDB.SB_JL_CZZSNBQYSJ";
	public CzzsnbqysjTbl(ORManager manager) {
		super(manager, tabName, Czzsnbtzzsj.class);

	}

}
