/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 11-Ê®ÔÂ-2003 15:04:29
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Gtgshwszz;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class GtgshwszzTbl extends ORTable {
        static final String tabName = "SBDB.SB_JL_GTGSHWSZZ";
        public GtgshwszzTbl(ORManager manager) {
                super(manager, tabName, Gtgshwszz.class);

        }

}
