/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 09-ÈýÔÂ-2004 11:35:14
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Gzsxpl;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class GzsxplTbl extends ORTable {
	static final String tabName = "SBDB.SB_JL_GZSXPL";
	public GzsxplTbl(ORManager manager) {
		super(manager, tabName, Gzsxpl.class);

	}

}
