/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 02-¾ÅÔÂ-2003 14:16:06
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;

import java.util.*;
import com.ekernel.db.connection.*;
import com.ekernel.db.or.*;
import java.sql.DriverManager;
import java.sql.Driver;

public class ORMgr extends ORManager
{
    public ORMgr()
    {
    }

    public final void _initDB()
    {
        register(new QyjbcwzbTbl(this));
        register(new HdzstzzsbTbl(this));
        register(new QysdsksTbl(this));
        register(new QysdsjdTbl(this));
        register(new LswszsbhzTbl(this));
        register(new SbjkmxTbl(this));
        register(new JjlxglszsmTbl(this));
        register(new GtgshsdszTbl(this));
        register(new GzsxTbl(this));
        register(new CzzsnbfpblTbl(this));
        register(new GtgshyysrmxTbl(this));
        register(new CzqrlTbl(this));
        register(new LsswszmxTbl(this));
        register(new QysdsnbTbl(this));
        register(new SydwshttsrmxTbl(this));
        register(new YhsgmzTbl(this));
        register(new YhsgmmxTbl(this));
        register(new SdwszsbhzTbl(this));
        register(new LsswszzTbl(this));
        register(new JqszTbl(this));
        register(new YhsspmzTbl(this));
        register(new SzzqszTbl(this));
        register(new SydwshttwhTbl(this));
        register(new CzzsnbqyTbl(this));
        register(new ZqlxTbl(this));
        register(new SzsmyfjsTbl(this));
        register(new CzzsnbzbTbl(this));
        register(new CzzsnbtzzsjTbl(this));
        register(new LygfTbl(this));
        register(new GrsdsmxTbl(this));
        register(new SbjkzbTbl(this));
        register(new SzsmTbl(this));
        register(new GtgshyysrzTbl(this));
        register(new SbbxmdzbTbl(this));
        register(new CzzsjbqysjTbl(this));
        register(new GtgshsdsmxTbl(this));
        register(new CzzsjbtzzsjTbl(this));
        register(new JmTbl(this));
        register(new SydwshttsrzbTbl(this));
        register(new WbhsTbl(this));
        register(new ClbjTbl(this));
        register(new YhsbgmxTbl(this));
        register(new WqyysTbl(this));
        register(new SqsbtmpTbl(this));
        register(new DsdzdkmxTbl(this));
        register(new ZqrlTbl(this));
        register(new GzsxlsTbl(this));
        register(new HdzsqysbTbl(this));
        register(new GrsdszTbl(this));
        register(new SbbbxmTbl(this));
        register(new YhsbgzTbl(this));
        register(new SwjgzzjgTbl(this));
        register(new GjTbl(this));
        register(new ZyTbl(this));
        register(new ZjlxTbl(this));
        register(new YhTbl(this));
        register(new GtgshwszmxTbl(this));
        register(new GtgshwszzTbl(this));
        register(new GtgshwszsbhzTbl(this));
        register(new YsjcTbl(this));
        register(new GjbzhyTbl(this));
        register(new YskmTbl(this));
        register(new LsgxTbl(this));
        register(new DjzclxTbl(this));
        register(new CzzsnbtzzmxsjTbl(this));
        register(new SklxTbl(this));
        register(new JmflTbl(this));
        register(new ZrrgrsdsmxTbl(this));
        register(new ZrrgrsdszTbl(this));
		register(new SkfdqkTbl(this));
		register(new WbzhrmbTbl(this));
		register(new GzsxplTbl(this));
        register(new PropertiesTbl(this));
        register(new YhkkhzxxTbl(this));
        register(new YhkkxxTbl(this));
		register(new GtgshZtTbl(this));
        register(new WynsksbTbl(this));
        register(new WynskszsmTbl(this));
        register(new ZjyjmsbzTbl(this));
        register(new Zjyjmsbmx12Tbl(this));
        register(new Zjyjmsbmx3Tbl(this));
        register(new SbjkclrzTbl(this));
        register(new Sbjkzb_HisTbl(this));
        register(new Sbjkmx_HisTbl(this));        
        register(new CZFWBGXXTBL(this));        
        register(new CZFWJBXXTBL(this));        
        register(new CZTDBGXXTBL(this));        
        register(new CZTDJBXXTBL(this)); 
        
        register(new CZUFWBGXXTBL(this));        
        register(new CZUFWJBXXTBL(this));        
        register(new CZUTDBGXXTBL(this));        
        register(new CZUTDJBXXTBL(this)); 
        
        register(new ZYFWBGXXTBL(this));        
        register(new ZYFWJBXXTBL(this));        
        register(new ZYTDBGXXTBL(this));        
        register(new ZYTDJBXXTBL(this)); 
        
        register(new JMZCTBL(this)); 
        register(new FTCDJZBTBL(this));
        register(new JnjpjsgzlxTbl(this));
        register(new WssbyyTbl(this));
        register(new ZjqyjmslxTbl(this));
             
    }
}