/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 20-Ê®ÔÂ-2003 11:22:45
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Properties;
import com.ekernel.db.or.*;
//import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class PropertiesTbl extends ORTable {
	static final String tabName = "SBDB.SB_JL_PROPERTIES";
	public PropertiesTbl(ORManager manager) {
		super(manager, tabName, com.ttsoft.bjtax.shenbao.model.domain.Properties.class);

	}

}
