/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 02-¾ÅÔÂ-2003 13:37:54
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Qyjbcwzb;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class QyjbcwzbTbl extends ORTable {
	static final String tabName = "SBDB.SB_JL_QYJBCWZB";
	public QyjbcwzbTbl(ORManager manager) {
		super(manager, tabName, Qyjbcwzb.class);

	}

}
