/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 19-Ê®Ò»ÔÂ-2003 20:46:23
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Skfdqk;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class SkfdqkTbl extends ORTable {
	static final String tabName = "DMDB.DJ_DM_SKFDQK";
	public SkfdqkTbl(ORManager manager) {
		super(manager, tabName, Skfdqk.class);

	}

}
