/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 20-Ê®Ò»ÔÂ-2003 14:49:39
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Wbzhrmb;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class WbzhrmbTbl extends ORTable {
	static final String tabName = "SBDB.SB_JL_WBZHRMB";
	public WbzhrmbTbl(ORManager manager) {
		super(manager, tabName, Wbzhrmb.class);

	}

}
