/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 28-Ê®¶þÔÂ-2004 14:56:43
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Yhkkhzxx;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class YhkkhzxxTbl extends ORTable {
	static final String tabName = "SFDB.SF_JL_GTGSH_YHKKHZXX";
	public YhkkhzxxTbl(ORManager manager) {
		super(manager, tabName, Yhkkhzxx.class);

	}

}
