/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 28-Ê®¶þÔÂ-2004 15:04:53
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Yhkkxx;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class YhkkxxTbl extends ORTable {
	static final String tabName = "SFDB.SF_JL_GTGSH_YHKKXX";
	public YhkkxxTbl(ORManager manager) {
		super(manager, tabName, Yhkkxx.class);

	}

}
