/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 02-¾ÅÔÂ-2003 14:16:06
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Yhsgmz;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class YhsgmzTbl extends ORTable {
	static final String tabName = "SBDB.SB_JL_YHSGMZ";
	public YhsgmzTbl(ORManager manager) {
		super(manager, tabName, Yhsgmz.class);

	}

}
