/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 17-Ê®Ò»ÔÂ-2003 21:14:35
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Zrrgrsdsz;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class ZrrgrsdszTbl extends ORTable {
	static final String tabName = "SBDB.SB_JL_ZRRGRSDSZ";
	public ZrrgrsdszTbl(ORManager manager) {
		super(manager, tabName, Zrrgrsdsz.class);

	}

}
