/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 03-¾ÅÔÂ-2003 14:55:08
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ttsoft.bjtax.shenbao.model.domain.Zy;
import com.ekernel.db.or.*;
import java.util.*;
import java.sql.Timestamp;
import java.math.BigDecimal;
public class ZyTbl extends ORTable {
	static final String tabName = "DMDB.DJ_DM_ZY";
	public ZyTbl(ORManager manager) {
		super(manager, tabName, Zy.class);

	}

}
