/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-°ËÔÂ-2006 13:06:31
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.mapping;
import com.ekernel.db.or.ORManager;
import com.ekernel.db.or.ORTable;
import com.ttsoft.bjtax.shenbao.model.domain.ZYTDBGXX;
public class ZYTDBGXXTBL extends ORTable {
	static final String tabName = "SFDB.SF_JL_ZYTDBGXX";
	public ZYTDBGXXTBL(ORManager manager) {
		super(manager, tabName, ZYTDBGXX.class);

	}

}
