/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:34:43
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Clbj implements ORObject {

	String clbjdm;
	String clbjmc;
	String bz;
	Timestamp cjrq;
	String sjsyztbs;
	public Clbj () {}
	public String getClbjdm() {
		return clbjdm;
	}
	public String getClbjmc() {
		return clbjmc;
	}
	public String getBz() {
		return bz;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getSjsyztbs() {
		return sjsyztbs;
	}
	public void setClbjdm( String _clbjdm ) {
		clbjdm = _clbjdm;
	}
	public void setClbjmc( String _clbjmc ) {
		clbjmc = _clbjmc;
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSjsyztbs( String _sjsyztbs ) {
		sjsyztbs = _sjsyztbs;
	}

}
