/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-八月-2006 13:07:56
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class CZFWBGXX implements ORObject {

	String bgqbz;
	String bghbz;
	String lrr;
	Timestamp fhrq;
	String bgqfwzl;
	String bghcqzsh;
	String fhr;
	double bghnzjsr;
	String cjr;
	String bgqcqzsh;
	Timestamp lrrq;
	double bgqnzjsr;
	String id;
	String fhbs;
	String djbh;
	String jcbh;
	String bghfwzl;
	double bghnynse;
	String bglx;
	Timestamp cjrq;
	String swjgzzjgdm;
	Timestamp tbrq;
	String jsjdm;
	double bgqnynse;
	String qxdm;
	
	/**
	 * 出租房屋原值
	 * add by wofei 2009-2-3
	 */
	double bgqczfwyz;
	/**
	 * 出租房屋原值
	 * add by wofei 2009-2-3
	 */
	double bghczfwyz;
	/**
	 * 按市场价格向个人出租用于居住的住房
	 * add by wofei 2009-2-3
	 */
	String bgqxgrczbs;
	/**
	 * 按市场价格向个人出租用于居住的住房
	 * add by wofei 2009-2-3
	 */
	String bghxgrczbs;
	
	public CZFWBGXX () {}
	public String getBgqbz() {
		return bgqbz;
	}
	public String getBghbz() {
		return bghbz;
	}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getFhrq() {
		return fhrq;
	}
	public String getBgqfwzl() {
		return bgqfwzl;
	}
	public String getBghcqzsh() {
		return bghcqzsh;
	}
	public String getFhr() {
		return fhr;
	}
	public double getBghnzjsr() {
		return bghnzjsr;
	}
	public String getCjr() {
		return cjr;
	}
	public String getBgqcqzsh() {
		return bgqcqzsh;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public double getBgqnzjsr() {
		return bgqnzjsr;
	}
	public String getId() {
		return id;
	}
	public String getFhbs() {
		return fhbs;
	}
	public String getDjbh() {
		return djbh;
	}
	public String getJcbh() {
		return jcbh;
	}
	public String getBghfwzl() {
		return bghfwzl;
	}
	public double getBghnynse() {
		return bghnynse;
	}
	public String getBglx() {
		return bglx;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public Timestamp getTbrq() {
		return tbrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public double getBgqnynse() {
		return bgqnynse;
	}
	public String getQxdm() {
		return qxdm;
	}
	public void setBgqbz( String _bgqbz ) {
		bgqbz = _bgqbz;
	}
	public void setBghbz( String _bghbz ) {
		bghbz = _bghbz;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setFhrq( Timestamp _fhrq ) {
		fhrq = _fhrq;
	}
	public void setBgqfwzl( String _bgqfwzl ) {
		bgqfwzl = _bgqfwzl;
	}
	public void setBghcqzsh( String _bghcqzsh ) {
		bghcqzsh = _bghcqzsh;
	}
	public void setFhr( String _fhr ) {
		fhr = _fhr;
	}
	public void setBghnzjsr( double _bghnzjsr ) {
		bghnzjsr = _bghnzjsr;
	}
	public void setBghnzjsr( BigDecimal _bghnzjsr ) {
		bghnzjsr = _bghnzjsr.doubleValue();
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setBgqcqzsh( String _bgqcqzsh ) {
		bgqcqzsh = _bgqcqzsh;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setBgqnzjsr( double _bgqnzjsr ) {
		bgqnzjsr = _bgqnzjsr;
	}
	public void setBgqnzjsr( BigDecimal _bgqnzjsr ) {
		bgqnzjsr = _bgqnzjsr.doubleValue();
	}
	public void setId( String _id ) {
		id = _id;
	}
	public void setFhbs( String _fhbs ) {
		fhbs = _fhbs;
	}
	public void setDjbh( String _djbh ) {
		djbh = _djbh;
	}
	public void setJcbh( String _jcbh ) {
		jcbh = _jcbh;
	}
	public void setBghfwzl( String _bghfwzl ) {
		bghfwzl = _bghfwzl;
	}
	public void setBghnynse( double _bghnynse ) {
		bghnynse = _bghnynse;
	}
	public void setBghnynse( BigDecimal _bghnynse ) {
		bghnynse = _bghnynse.doubleValue();
	}
	public void setBglx( String _bglx ) {
		bglx = _bglx;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setTbrq( Timestamp _tbrq ) {
		tbrq = _tbrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setBgqnynse( double _bgqnynse ) {
		bgqnynse = _bgqnynse;
	}
	public void setBgqnynse( BigDecimal _bgqnynse ) {
		bgqnynse = _bgqnynse.doubleValue();
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public double getBghczfwyz() {
		return bghczfwyz;
	}
	public void setBghczfwyz(double bghczfwyz) {
		this.bghczfwyz = bghczfwyz;
	}
	public void setBghczfwyz(BigDecimal bghczfwyz) {
		this.bghczfwyz = bghczfwyz.doubleValue();
	}
	public String getBgqxgrczbs() {
		return bgqxgrczbs;
	}
	public void setBgqxgrczbs(String bgqxgrczbs) {
		this.bgqxgrczbs = bgqxgrczbs;
	}
	public double getBgqczfwyz() {
		return bgqczfwyz;
	}
	public void setBgqczfwyz(double bgqczfwyz) {
		this.bgqczfwyz = bgqczfwyz;
	}
	public void setBgqczfwyz(BigDecimal bgqczfwyz) {
		this.bgqczfwyz = bgqczfwyz.doubleValue();
	}
	public String getBghxgrczbs() {
		return bghxgrczbs;
	}
	public void setBghxgrczbs(String bghxgrczbs) {
		this.bghxgrczbs = bghxgrczbs;
	}
}
