/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-°ËÔÂ-2006 13:07:56
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class CZTDBGXX implements ORObject {

	String bgqtdzsh;
	String bgqbz;
	String bghbz;
	String lrr;
	Timestamp fhrq;
	double bghqzmsmj;
	String bghtdzl;
	double bghmpfmse;
	double bgqqzysmj;
	String fhr;
	String cjr;
	double bgqtdmj;
	Timestamp lrrq;
	double bgqqzmsmj;
	String id;
	String fhbs;
	String djbh;
	String jcbh;
	double bgqmpfmse;
	double bghnynse;
	String bglx;
	Timestamp cjrq;
	String swjgzzjgdm;
	String bgqtdzl;
	Timestamp tbrq;
	String jsjdm;
	String bghtdzsh;
	double bghtdmj;
	double bgqnynse;
	String qxdm;
	double bghqzysmj;
	public CZTDBGXX () {}
	public String getBgqtdzsh() {
		return bgqtdzsh;
	}
	public String getBgqbz() {
		return bgqbz;
	}
	public String getBghbz() {
		return bghbz;
	}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getFhrq() {
		return fhrq;
	}
	public double getBghqzmsmj() {
		return bghqzmsmj;
	}
	public String getBghtdzl() {
		return bghtdzl;
	}
	public double getBghmpfmse() {
		return bghmpfmse;
	}
	public double getBgqqzysmj() {
		return bgqqzysmj;
	}
	public String getFhr() {
		return fhr;
	}
	public String getCjr() {
		return cjr;
	}
	public double getBgqtdmj() {
		return bgqtdmj;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public double getBgqqzmsmj() {
		return bgqqzmsmj;
	}
	public String getId() {
		return id;
	}
	public String getFhbs() {
		return fhbs;
	}
	public String getDjbh() {
		return djbh;
	}
	public String getJcbh() {
		return jcbh;
	}
	public double getBgqmpfmse() {
		return bgqmpfmse;
	}
	public double getBghnynse() {
		return bghnynse;
	}
	public String getBglx() {
		return bglx;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public String getBgqtdzl() {
		return bgqtdzl;
	}
	public Timestamp getTbrq() {
		return tbrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getBghtdzsh() {
		return bghtdzsh;
	}
	public double getBghtdmj() {
		return bghtdmj;
	}
	public double getBgqnynse() {
		return bgqnynse;
	}
	public String getQxdm() {
		return qxdm;
	}
	public double getBghqzysmj() {
		return bghqzysmj;
	}
	public void setBgqtdzsh( String _bgqtdzsh ) {
		bgqtdzsh = _bgqtdzsh;
	}
	public void setBgqbz( String _bgqbz ) {
		bgqbz = _bgqbz;
	}
	public void setBghbz( String _bghbz ) {
		bghbz = _bghbz;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setFhrq( Timestamp _fhrq ) {
		fhrq = _fhrq;
	}
	public void setBghqzmsmj( double _bghqzmsmj ) {
		bghqzmsmj = _bghqzmsmj;
	}
	public void setBghqzmsmj( BigDecimal _bghqzmsmj ) {
		bghqzmsmj = _bghqzmsmj.doubleValue();
	}
	public void setBghtdzl( String _bghtdzl ) {
		bghtdzl = _bghtdzl;
	}
	public void setBghmpfmse( double _bghmpfmse ) {
		bghmpfmse = _bghmpfmse;
	}
	public void setBghmpfmse( BigDecimal _bghmpfmse ) {
		bghmpfmse = _bghmpfmse.doubleValue();
	}
	public void setBgqqzysmj( double _bgqqzysmj ) {
		bgqqzysmj = _bgqqzysmj;
	}
	public void setBgqqzysmj( BigDecimal _bgqqzysmj ) {
		bgqqzysmj = _bgqqzysmj.doubleValue();
	}
	public void setFhr( String _fhr ) {
		fhr = _fhr;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setBgqtdmj( double _bgqtdmj ) {
		bgqtdmj = _bgqtdmj;
	}
	public void setBgqtdmj( BigDecimal _bgqtdmj ) {
		bgqtdmj = _bgqtdmj.doubleValue();
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setBgqqzmsmj( double _bgqqzmsmj ) {
		bgqqzmsmj = _bgqqzmsmj;
	}
	public void setBgqqzmsmj( BigDecimal _bgqqzmsmj ) {
		bgqqzmsmj = _bgqqzmsmj.doubleValue();
	}
	public void setId( String _id ) {
		id = _id;
	}
	public void setFhbs( String _fhbs ) {
		fhbs = _fhbs;
	}
	public void setDjbh( String _djbh ) {
		djbh = _djbh;
	}
	public void setJcbh( String _jcbh ) {
		jcbh = _jcbh;
	}
	public void setBgqmpfmse( double _bgqmpfmse ) {
		bgqmpfmse = _bgqmpfmse;
	}
	public void setBgqmpfmse( BigDecimal _bgqmpfmse ) {
		bgqmpfmse = _bgqmpfmse.doubleValue();
	}
	public void setBghnynse( double _bghnynse ) {
		bghnynse = _bghnynse;
	}
	public void setBghnynse( BigDecimal _bghnynse ) {
		bghnynse = _bghnynse.doubleValue();
	}
	public void setBglx( String _bglx ) {
		bglx = _bglx;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setBgqtdzl( String _bgqtdzl ) {
		bgqtdzl = _bgqtdzl;
	}
	public void setTbrq( Timestamp _tbrq ) {
		tbrq = _tbrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setBghtdzsh( String _bghtdzsh ) {
		bghtdzsh = _bghtdzsh;
	}
	public void setBghtdmj( double _bghtdmj ) {
		bghtdmj = _bghtdmj;
	}
	public void setBghtdmj( BigDecimal _bghtdmj ) {
		bghtdmj = _bghtdmj.doubleValue();
	}
	public void setBgqnynse( double _bgqnynse ) {
		bgqnynse = _bgqnynse;
	}
	public void setBgqnynse( BigDecimal _bgqnynse ) {
		bgqnynse = _bgqnynse.doubleValue();
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public void setBghqzysmj( double _bghqzysmj ) {
		bghqzysmj = _bghqzysmj;
	}
	public void setBghqzysmj( BigDecimal _bghqzysmj ) {
		bghqzysmj = _bghqzysmj.doubleValue();
	}

}
