/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-°ËÔÂ-2006 13:07:56
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class CZUFWJBXX implements ORObject {

	String lrr;
	double nzj;
	Timestamp fhrq;
	String czrmc;
	String czrzjhm;
	String fhr;
	String cjr;
	Timestamp lrrq;
	String czfwzl;
	String zjlxdm;
	String id;
	String fhbs;
	String djbh;
	String bz;
	Timestamp cjrq;
	String swjgzzjgdm;
	Timestamp tbrq;
	String jsjdm;
	String qxdm;
	String zlqxdm;
	
	public CZUFWJBXX () {}
	public String getLrr() {
		return lrr;
	}
	public double getNzj() {
		return nzj;
	}
	public Timestamp getFhrq() {
		return fhrq;
	}
	public String getCzrmc() {
		return czrmc;
	}
	public String getCzrzjhm() {
		return czrzjhm;
	}
	public String getFhr() {
		return fhr;
	}
	public String getCjr() {
		return cjr;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getCzfwzl() {
		return czfwzl;
	}
	public String getZjlxdm() {
		return zjlxdm;
	}
	public String getId() {
		return id;
	}
	public String getFhbs() {
		return fhbs;
	}
	public String getDjbh() {
		return djbh;
	}
	public String getBz() {
		return bz;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public Timestamp getTbrq() {
		return tbrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getQxdm() {
		return qxdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setNzj( double _nzj ) {
		nzj = _nzj;
	}
	public void setNzj( BigDecimal _nzj ) {
		nzj = _nzj.doubleValue();
	}
	public void setFhrq( Timestamp _fhrq ) {
		fhrq = _fhrq;
	}
	public void setCzrmc( String _czrmc ) {
		czrmc = _czrmc;
	}
	public void setCzrzjhm( String _czrzjhm ) {
		czrzjhm = _czrzjhm;
	}
	public void setFhr( String _fhr ) {
		fhr = _fhr;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setCzfwzl( String _czfwzl ) {
		czfwzl = _czfwzl;
	}
	public void setZjlxdm( String _zjlxdm ) {
		zjlxdm = _zjlxdm;
	}
	public void setId( String _id ) {
		id = _id;
	}
	public void setFhbs( String _fhbs ) {
		fhbs = _fhbs;
	}
	public void setDjbh( String _djbh ) {
		djbh = _djbh;
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setTbrq( Timestamp _tbrq ) {
		tbrq = _tbrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public String getZlqxdm() {
		return zlqxdm;
	}
	public void setZlqxdm(String zlqxdm) {
		this.zlqxdm = zlqxdm;
	}

}
