/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-°ËÔÂ-2006 13:07:56
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class CZUFWBGXX implements ORObject {

	String bgqbz;
	String bghbz;
	String lrr;
	double bghnzj;
	Timestamp fhrq;
	String bghczrmc;
	String bgqzjlxdm;
	String bgqczfwzl;
	String fhr;
	String cjr;
	String bgqczrzjhm;
	double bgqnzj;
	String bgqczrmc;
	Timestamp lrrq;
	String id;
	String fhbs;
	String djbh;
	String jcbh;
	String bglx;
	Timestamp cjrq;
	String swjgzzjgdm;
	Timestamp tbrq;
	String jsjdm;
	String bghczrzjhm;
	String qxdm;
	String bghzjlxdm;
	String bghczfwzl;
	
	String bgqzlqxdm;
	String bghzlqxdm;
	
	public CZUFWBGXX () {}
	public String getBgqbz() {
		return bgqbz;
	}
	public String getBghbz() {
		return bghbz;
	}
	public String getLrr() {
		return lrr;
	}
	public double getBghnzj() {
		return bghnzj;
	}
	public Timestamp getFhrq() {
		return fhrq;
	}
	public String getBghczrmc() {
		return bghczrmc;
	}
	public String getBgqzjlxdm() {
		return bgqzjlxdm;
	}
	public String getBgqczfwzl() {
		return bgqczfwzl;
	}
	public String getFhr() {
		return fhr;
	}
	public String getCjr() {
		return cjr;
	}
	public String getBgqczrzjhm() {
		return bgqczrzjhm;
	}
	public double getBgqnzj() {
		return bgqnzj;
	}
	public String getBgqczrmc() {
		return bgqczrmc;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getId() {
		return id;
	}
	public String getFhbs() {
		return fhbs;
	}
	public String getDjbh() {
		return djbh;
	}
	public String getJcbh() {
		return jcbh;
	}
	public String getBglx() {
		return bglx;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public Timestamp getTbrq() {
		return tbrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getBghczrzjhm() {
		return bghczrzjhm;
	}
	public String getQxdm() {
		return qxdm;
	}
	public String getBghzjlxdm() {
		return bghzjlxdm;
	}
	public String getBghczfwzl() {
		return bghczfwzl;
	}
	public void setBgqbz( String _bgqbz ) {
		bgqbz = _bgqbz;
	}
	public void setBghbz( String _bghbz ) {
		bghbz = _bghbz;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setBghnzj( double _bghnzj ) {
		bghnzj = _bghnzj;
	}
	public void setBghnzj( BigDecimal _bghnzj ) {
		bghnzj = _bghnzj.doubleValue();
	}
	public void setFhrq( Timestamp _fhrq ) {
		fhrq = _fhrq;
	}
	public void setBghczrmc( String _bghczrmc ) {
		bghczrmc = _bghczrmc;
	}
	public void setBgqzjlxdm( String _bgqzjlxdm ) {
		bgqzjlxdm = _bgqzjlxdm;
	}
	public void setBgqczfwzl( String _bgqczfwzl ) {
		bgqczfwzl = _bgqczfwzl;
	}
	public void setFhr( String _fhr ) {
		fhr = _fhr;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setBgqczrzjhm( String _bgqczrzjhm ) {
		bgqczrzjhm = _bgqczrzjhm;
	}
	public void setBgqnzj( double _bgqnzj ) {
		bgqnzj = _bgqnzj;
	}
	public void setBgqnzj( BigDecimal _bgqnzj ) {
		bgqnzj = _bgqnzj.doubleValue();
	}
	public void setBgqczrmc( String _bgqczrmc ) {
		bgqczrmc = _bgqczrmc;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setId( String _id ) {
		id = _id;
	}
	public void setFhbs( String _fhbs ) {
		fhbs = _fhbs;
	}
	public void setDjbh( String _djbh ) {
		djbh = _djbh;
	}
	public void setJcbh( String _jcbh ) {
		jcbh = _jcbh;
	}
	public void setBglx( String _bglx ) {
		bglx = _bglx;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setTbrq( Timestamp _tbrq ) {
		tbrq = _tbrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setBghczrzjhm( String _bghczrzjhm ) {
		bghczrzjhm = _bghczrzjhm;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public void setBghzjlxdm( String _bghzjlxdm ) {
		bghzjlxdm = _bghzjlxdm;
	}
	public void setBghczfwzl( String _bghczfwzl ) {
		bghczfwzl = _bghczfwzl;
	}
	public String getBghzlqxdm() {
		return bghzlqxdm;
	}
	public void setBghzlqxdm(String bghzlqxdm) {
		this.bghzlqxdm = bghzlqxdm;
	}
	public String getBgqzlqxdm() {
		return bgqzlqxdm;
	}
	public void setBgqzlqxdm(String bgqzlqxdm) {
		this.bgqzlqxdm = bgqzlqxdm;
	}


}
