/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 22-°ËÔÂ-2006 15:51:42
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class CZUTDJBXX implements ORObject {

	String lrr;
	Timestamp fhrq;
	String cztdzl;
	String czrmc;
	String czrzjhm;
	String fhr;
	String cjr;
	double tdmj;
	Timestamp lrrq;
	String zjlxdm;
	String id;
	String fhbs;
	String djbh;
	String bz;
	Timestamp cjrq;
	String swjgzzjgdm;
	String jsjdm;
	Timestamp tbrq;
	String qxdm;
	String zlqxdm;
	String sfjnws;
	
	public String getSfjnws() {
		return sfjnws;
	}
	public void setSfjnws(String sfjnws) {
		this.sfjnws = sfjnws;
	}
	public CZUTDJBXX () {}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getFhrq() {
		return fhrq;
	}
	public String getCztdzl() {
		return cztdzl;
	}
	public String getCzrmc() {
		return czrmc;
	}
	public String getCzrzjhm() {
		return czrzjhm;
	}
	public String getFhr() {
		return fhr;
	}
	public String getCjr() {
		return cjr;
	}
	public double getTdmj() {
		return tdmj;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getZjlxdm() {
		return zjlxdm;
	}
	public String getId() {
		return id;
	}
	public String getFhbs() {
		return fhbs;
	}
	public String getDjbh() {
		return djbh;
	}
	public String getBz() {
		return bz;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public Timestamp getTbrq() {
		return tbrq;
	}
	public String getQxdm() {
		return qxdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setFhrq( Timestamp _fhrq ) {
		fhrq = _fhrq;
	}
	public void setCztdzl( String _cztdzl ) {
		cztdzl = _cztdzl;
	}
	public void setCzrmc( String _czrmc ) {
		czrmc = _czrmc;
	}
	public void setCzrzjhm( String _czrzjhm ) {
		czrzjhm = _czrzjhm;
	}
	public void setFhr( String _fhr ) {
		fhr = _fhr;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setTdmj( double _tdmj ) {
		tdmj = _tdmj;
	}
	public void setTdmj( BigDecimal _tdmj ) {
		tdmj = _tdmj.doubleValue();
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setZjlxdm( String _zjlxdm ) {
		zjlxdm = _zjlxdm;
	}
	public void setId( String _id ) {
		id = _id;
	}
	public void setFhbs( String _fhbs ) {
		fhbs = _fhbs;
	}
	public void setDjbh( String _djbh ) {
		djbh = _djbh;
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setTbrq( Timestamp _tbrq ) {
		tbrq = _tbrq;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public String getZlqxdm() {
		return zlqxdm;
	}
	public void setZlqxdm(String zlqxdm) {
		this.zlqxdm = zlqxdm;
	}


	


}
