/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:35:43
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Czzsnbtzzsj implements ORObject {

	String zjlxdm;
	String jsjdm;
	String zjhm;
	String cwfzr;
	String tzzxm;
	String nd;
    String swjgzzjgdm;
    String qxdm;
    Timestamp cjrq;
    Timestamp lrrq;
	public Czzsnbtzzsj () {}
	public String getZjlxdm() {
		return zjlxdm;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getZjhm() {
		return zjhm;
	}
	public String getCwfzr() {
		return cwfzr;
	}
	public String getTzzxm() {
		return tzzxm;
	}
	public String getNd() {
		return nd;
	}

        public String getSwjgzzjgdm()
        {
            return swjgzzjgdm;
        }

	public void setZjlxdm( String _zjlxdm ) {
		zjlxdm = _zjlxdm;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setZjhm( String _zjhm ) {
		zjhm = _zjhm;
	}
	public void setCwfzr( String _cwfzr ) {
		cwfzr = _cwfzr;
	}
	public void setTzzxm( String _tzzxm ) {
		tzzxm = _tzzxm;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}

        public void setSwjgzzjgdm(String _swjgzzjgdm)
        {
            swjgzzjgdm = _swjgzzjgdm;
        }
    public Timestamp getCjrq()
    {
        return cjrq;
    }
    public void setCjrq(Timestamp cjrq)
    {
        this.cjrq = cjrq;
    }
    public Timestamp getLrrq()
    {
        return lrrq;
    }
    public void setLrrq(Timestamp lrrq)
    {
        this.lrrq = lrrq;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }

}
