/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:35:39
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Czzsjbtzzsj implements ORObject {

	Timestamp lrrq;
	BigDecimal qcwjsdse;
	BigDecimal sjyjse;
	String tzzxm;
	String jsjdm;
	String zjhm;
	BigDecimal ynssde;
	String nd;
	String zjlxdm;
	BigDecimal sysl;
	BigDecimal jmse;
	String jd;
	BigDecimal sskcs;
	BigDecimal ynsdse;
	BigDecimal fpbl;
	BigDecimal yjnsdse;
    String swjgzzjgdm;
    Timestamp cjrq;
    String qxdm;

	public Czzsjbtzzsj () {}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public BigDecimal getQcwjsdse() {
		return qcwjsdse;
	}
	public BigDecimal getSjyjse() {
		return sjyjse;
	}
	public String getTzzxm() {
		return tzzxm;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getZjhm() {
		return zjhm;
	}
	public BigDecimal getYnssde() {
		return ynssde;
	}
	public String getNd() {
		return nd;
	}
	public String getZjlxdm() {
		return zjlxdm;
	}
	public BigDecimal getSysl() {
		return sysl;
	}
	public BigDecimal getJmse() {
		return jmse;
	}
	public String getJd() {
		return jd;
	}
	public BigDecimal getSskcs() {
		return sskcs;
	}
	public BigDecimal getYnsdse() {
		return ynsdse;
	}
	public BigDecimal getFpbl() {
		return fpbl;
	}
	public BigDecimal getYjnsdse() {
		return yjnsdse;
	}

        public String getSwjgzzjgdm()
        {
            return swjgzzjgdm;
        }

	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setQcwjsdse( BigDecimal _qcwjsdse ) {
		qcwjsdse = _qcwjsdse;
	}
	public void setSjyjse( BigDecimal _sjyjse ) {
		sjyjse = _sjyjse ;
	}
	public void setTzzxm( String _tzzxm ) {
		tzzxm = _tzzxm;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setZjhm( String _zjhm ) {
		zjhm = _zjhm;
	}
	public void setYnssde( BigDecimal _ynssde ) {
		ynssde = _ynssde ;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setZjlxdm( String _zjlxdm ) {
		zjlxdm = _zjlxdm;
	}
	public void setSysl( BigDecimal _sysl ) {
		sysl = _sysl ;
	}
	public void setJmse( BigDecimal _jmse ) {
		jmse = _jmse ;
	}
	public void setJd( String _jd ) {
		jd = _jd;
	}
	public void setSskcs( BigDecimal _sskcs ) {
		sskcs = _sskcs ;
	}
	public void setYnsdse( BigDecimal _ynsdse ) {
		ynsdse = _ynsdse ;
	}
	public void setFpbl( BigDecimal _fpbl ) {
		fpbl = _fpbl ;
	}
	public void setYjnsdse( BigDecimal _yjnsdse ) {
		yjnsdse = _yjnsdse ;
	}

        public void setSwjgzzjgdm(String _swjgzzjgdm)
        {
            swjgzzjgdm = _swjgzzjgdm;
        }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }
    public Timestamp getCjrq()
    {
        return cjrq;
    }
    public void setCjrq(Timestamp cjrq)
    {
        this.cjrq = cjrq;
    }

}
