/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 20-Ê®ÔÂ-2003 11:22:45
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Djzclx implements ORObject {

	String djzclxmc;
	Timestamp lrrq;
	String nwzfldm;
	String pclxdm;
	String zxbs;
	String qylxdm;
	String swdjzzldm;
	String djzclxdm;
	String lrr;
	Timestamp zhgxsj;
	public Djzclx () {}
	public String getDjzclxmc() {
		return djzclxmc;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getNwzfldm() {
		return nwzfldm;
	}
	public String getPclxdm() {
		return pclxdm;
	}
	public String getZxbs() {
		return zxbs;
	}
	public String getQylxdm() {
		return qylxdm;
	}
	public String getSwdjzzldm() {
		return swdjzzldm;
	}
	public String getDjzclxdm() {
		return djzclxdm;
	}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getZhgxsj() {
		return zhgxsj;
	}
	public void setDjzclxmc( String _djzclxmc ) {
		djzclxmc = _djzclxmc;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setNwzfldm( String _nwzfldm ) {
		nwzfldm = _nwzfldm;
	}
	public void setPclxdm( String _pclxdm ) {
		pclxdm = _pclxdm;
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setQylxdm( String _qylxdm ) {
		qylxdm = _qylxdm;
	}
	public void setSwdjzzldm( String _swdjzzldm ) {
		swdjzzldm = _swdjzzldm;
	}
	public void setDjzclxdm( String _djzclxdm ) {
		djzclxdm = _djzclxdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setZhgxsj( Timestamp _zhgxsj ) {
		zhgxsj = _zhgxsj;
	}

}
