/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:35:46
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Dsdzdkmx implements ORObject {

	Timestamp skssksrq;
	String lrr;
	Timestamp cjrq;
	String szdm;
	BigDecimal jsje;
	String sbhzdh;
	String fsdm;
	String szsmdm;
	Timestamp lrrq;
	String szmc;
	String wszh;
	BigDecimal sjse;
	String bz;
	String qylxdh;
	String szsmmc;
	String swjgzzjgdm;
	BigDecimal sl;
	String bdzrmc;
	String jsjdm;
	Timestamp skssjsrq;
    String pzzldm;
    String sjly;
    String nd;
    String qxdm;

	public Dsdzdkmx () {}
	public Timestamp getSkssksrq() {
		return skssksrq;
	}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getSzdm() {
		return szdm;
	}
	public BigDecimal getJsje() {
		return jsje;
	}
	public String getSbhzdh() {
		return sbhzdh;
	}
	public String getFsdm() {
		return fsdm;
	}
	public String getSzsmdm() {
		return szsmdm;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getSzmc() {
		return szmc;
	}
	public String getWszh() {
		return wszh;
	}
	public BigDecimal getSjse() {
		return sjse;
	}
	public String getBz() {
		return bz;
	}
	public String getQylxdh() {
		return qylxdh;
	}
	public String getSzsmmc() {
		return szsmmc;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public BigDecimal getSl() {
		return sl;
	}
	public String getBdzrmc() {
		return bdzrmc;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public Timestamp getSkssjsrq() {
		return skssjsrq;
	}
	public void setSkssksrq( Timestamp _skssksrq ) {
		skssksrq = _skssksrq;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSzdm( String _szdm ) {
		szdm = _szdm;
	}
	public void setJsje( BigDecimal _jsje ) {
		jsje = _jsje;
	}
	public void setSbhzdh( String _sbhzdh ) {
		sbhzdh = _sbhzdh;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
	public void setSzsmdm( String _szsmdm ) {
		szsmdm = _szsmdm;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setSzmc( String _szmc ) {
		szmc = _szmc;
	}
	public void setWszh( String _wszh ) {
		wszh = _wszh;
	}
	public void setSjse( BigDecimal _sjse ) {
		sjse = _sjse;
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setQylxdh( String _qylxdh ) {
		qylxdh = _qylxdh;
	}
	public void setSzsmmc( String _szsmmc ) {
		szsmmc = _szsmmc;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setSl( BigDecimal _sl ) {
		sl = _sl;
	}
	public void setBdzrmc( String _bdzrmc ) {
		bdzrmc = _bdzrmc;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setSkssjsrq( Timestamp _skssjsrq ) {
		skssjsrq = _skssjsrq;
	}
    public String getPzzldm()
    {
        return pzzldm;
    }
    public void setPzzldm(String pzzldm)
    {
        this.pzzldm = pzzldm;
    }
    public String getSjly()
    {
        return sjly;
    }
    public void setSjly(String sjly)
    {
        this.sjly = sjly;
    }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }

}
