/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-°ËÔÂ-2006 13:06:31
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class FTCDJZB implements ORObject {

	Timestamp lrrq;
	String qxdm;
	String djlx;
	String jsjdm;
	String djbh;
	String nsrsbh;
	Timestamp tbrq;
	String swjgzzjgdm;
	Timestamp cjrq;
	String cjr;
	String lrr;
	String fsdm;
	String nsrmc;
	public FTCDJZB () {}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getQxdm() {
		return qxdm;
	}
	public String getDjlx() {
		return djlx;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getDjbh() {
		return djbh;
	}
	public String getNsrsbh() {
		return nsrsbh;
	}
	public Timestamp getTbrq() {
		return tbrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getCjr() {
		return cjr;
	}
	public String getLrr() {
		return lrr;
	}
	public String getFsdm() {
		return fsdm;
	}
	public String getNsrmc() {
		return nsrmc;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public void setDjlx( String _djlx ) {
		djlx = _djlx;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setDjbh( String _djbh ) {
		djbh = _djbh;
	}
	public void setNsrsbh( String _nsrsbh ) {
		nsrsbh = _nsrsbh;
	}
	public void setTbrq( Timestamp _tbrq ) {
		tbrq = _tbrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
	public void setNsrmc( String _nsrmc ) {
		nsrmc = _nsrmc;
	}

}
