/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 03-¾ÅÔÂ-2003 14:53:53
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Gj implements ORObject {

	String lrr;
	String gjdqmc;
	Timestamp zhgxsj;
	String zxbs;
	Timestamp lrrq;
	String gjdqdm;
	public Gj () {}
	public String getLrr() {
		return lrr;
	}
	public String getGjdqmc() {
		return gjdqmc;
	}
	public Timestamp getZhgxsj() {
		return zhgxsj;
	}
	public String getZxbs() {
		return zxbs;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getGjdqdm() {
		return gjdqdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setGjdqmc( String _gjdqmc ) {
		gjdqmc = _gjdqmc;
	}
	public void setZhgxsj( Timestamp _zhgxsj ) {
		zhgxsj = _zhgxsj;
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setGjdqdm( String _gjdqdm ) {
		gjdqdm = _gjdqdm;
	}

}
