/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 20-Ê®ÔÂ-2003 11:22:46
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Gjbzhy implements ORObject {

	Timestamp lrrq;
	String gjbzhydm;
	String zghydm;
	String dfshydm;
	String zxbs;
	String cyfldm;
	String gjbzhymc;
	String lrr;
	String hymldm;
	Timestamp zhgxsj;
	public Gjbzhy () {}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getGjbzhydm() {
		return gjbzhydm;
	}
	public String getZghydm() {
		return zghydm;
	}
	public String getDfshydm() {
		return dfshydm;
	}
	public String getZxbs() {
		return zxbs;
	}
	public String getCyfldm() {
		return cyfldm;
	}
	public String getGjbzhymc() {
		return gjbzhymc;
	}
	public String getLrr() {
		return lrr;
	}
	public String getHymldm() {
		return hymldm;
	}
	public Timestamp getZhgxsj() {
		return zhgxsj;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setGjbzhydm( String _gjbzhydm ) {
		gjbzhydm = _gjbzhydm;
	}
	public void setZghydm( String _zghydm ) {
		zghydm = _zghydm;
	}
	public void setDfshydm( String _dfshydm ) {
		dfshydm = _dfshydm;
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setCyfldm( String _cyfldm ) {
		cyfldm = _cyfldm;
	}
	public void setGjbzhymc( String _gjbzhymc ) {
		gjbzhymc = _gjbzhymc;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setHymldm( String _hymldm ) {
		hymldm = _hymldm;
	}
	public void setZhgxsj( Timestamp _zhgxsj ) {
		zhgxsj = _zhgxsj;
	}

}
