/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:35:49
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Grsdsmx implements ORObject {

	BigDecimal jmje;
	String zymc;
	BigDecimal sre;
	Timestamp cjsj;
	BigDecimal ynssde;
	String xm;
	String szsmdm;
	Timestamp lrrq;
	String zjlxdm;
    String zjlxmc;
	String wszh;
	String gjdm;
	Timestamp sbrq;
	String zydm;
	String szsmmc;
	BigDecimal sl;
	String jsjdm;
	String zjhm;
	String gjmc;
	BigDecimal bqskse;
        String swjgzzjgdm;
        String nd;
	public Grsdsmx () {}
	public BigDecimal getJmje() {
		return jmje;
	}
	public String getZymc() {
		return zymc;
	}
	public BigDecimal getSre() {
		return sre;
	}
	public Timestamp getCjsj() {
		return cjsj;
	}
	public BigDecimal getYnssde() {
		return ynssde;
	}
	public String getXm() {
		return xm;
	}
	public String getSzsmdm() {
		return szsmdm;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getZjlxdm() {
		return zjlxdm;
	}
    public String getZjlxmc() {
        return zjlxmc;
    }
	public String getWszh() {
		return wszh;
	}
	public String getGjdm() {
		return gjdm;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public String getZydm() {
		return zydm;
	}
	public String getSzsmmc() {
		return szsmmc;
	}
	public BigDecimal getSl() {
		return sl;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getZjhm() {
		return zjhm;
	}
	public String getGjmc() {
		return gjmc;
	}
	public BigDecimal getBqskse() {
		return bqskse;
	}
	public void setJmje( BigDecimal _jmje ) {
		jmje = _jmje;
	}
	public void setZymc( String _zymc ) {
		zymc = _zymc;
	}
	public void setSre( BigDecimal _sre ) {
		sre = _sre;
	}
	public void setCjsj( Timestamp _cjsj ) {
		cjsj = _cjsj;
	}
	public void setYnssde( BigDecimal _ynssde ) {
		ynssde = _ynssde;
	}
	public void setXm( String _xm ) {
		xm = _xm;
	}
	public void setSzsmdm( String _szsmdm ) {
		szsmdm = _szsmdm;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setZjlxdm( String _zjlxdm ) {
		zjlxdm = _zjlxdm;
	}
    public void setZjlxmc( String _zjlxmc ) {
        zjlxmc = _zjlxmc;
    }
	public void setWszh( String _wszh ) {
		wszh = _wszh;
	}
	public void setGjdm( String _gjdm ) {
		gjdm = _gjdm;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setZydm( String _zydm ) {
		zydm = _zydm;
	}
	public void setSzsmmc( String _szsmmc ) {
		szsmmc = _szsmmc;
	}
	public void setSl( BigDecimal _sl ) {
		sl = _sl;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setZjhm( String _zjhm ) {
		zjhm = _zjhm;
	}
	public void setGjmc( String _gjmc ) {
		gjmc = _gjmc;
	}
	public void setBqskse( BigDecimal _bqskse ) {
		bqskse = _bqskse;
	}
  public String getSwjgzzjgdm() {
    return swjgzzjgdm;
  }
  public void setSwjgzzjgdm(String swjgzzjgdm) {
    this.swjgzzjgdm = swjgzzjgdm;
  }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
}
