/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:35:51
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Grsdsz implements ORObject {

	Timestamp lrrq;
	BigDecimal bqfdwzrs;
	BigDecimal bqdwzrs;
	Timestamp skssksrq;
	String jsjdm;
	Timestamp skssjsrq;
	Timestamp cjsj;
	String bz;
	Timestamp sbrq;
	String lrr;
	String fsdm;
//	String nsrmc;
    String swjgzzjgdm;
    String nd;

	public Grsdsz () {}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public BigDecimal getBqfdwzrs() {
		return bqfdwzrs;
	}
	public BigDecimal getBqdwzrs() {
		return bqdwzrs;
	}
	public Timestamp getSkssksrq() {
		return skssksrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public Timestamp getSkssjsrq() {
		return skssjsrq;
	}
	public Timestamp getCjsj() {
		return cjsj;
	}
	public String getBz() {
		return bz;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public String getLrr() {
		return lrr;
	}
	public String getFsdm() {
		return fsdm;
	}
//	public String getNsrmc() {
//		return nsrmc;
//	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setBqfdwzrs( BigDecimal _bqfdwzrs ) {
		bqfdwzrs = _bqfdwzrs;
	}
	public void setBqdwzrs( BigDecimal _bqdwzrs ) {
		bqdwzrs = _bqdwzrs;
	}
	public void setSkssksrq( Timestamp _skssksrq ) {
		skssksrq = _skssksrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setSkssjsrq( Timestamp _skssjsrq ) {
		skssjsrq = _skssjsrq;
	}
	public void setCjsj( Timestamp _cjsj ) {
		cjsj = _cjsj;
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
//	public void setNsrmc( String _nsrmc ) {
//		nsrmc = _nsrmc;
//	}
    public String getSwjgzzjgdm()  {
        return swjgzzjgdm;
    }
    public void setSwjgzzjgdm(String swjgzzjgdm)   {
        this.swjgzzjgdm = swjgzzjgdm;
    }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
}
