/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 11-Ê®ÔÂ-2003 14:09:01
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Gtgshwszz implements ORObject {

        String swjgzzjgmc;
        String lrr;
        String djzclxmc;
        Timestamp cjrq;
        String swjgzzjgdm2;
        String sbhzdh;
        Timestamp lrrq;
        String dz;
        String fsdm;
        String zjlxdm;
        String wszh;
        String pzzldm;
        String clbjdm;
        BigDecimal hjsjje;
        String jbdh;
        String swjgzzjgdm;
        String zjhm;
        String jsjdm;
        String djzclxdm;
        String gjbzhydm;
        String nsrjsjdm;
        String nd;
  private String wszxh;
    private String qxdm;
    private String ndzb;
        public Gtgshwszz () {}
        public String getSwjgzzjgmc() {
                return swjgzzjgmc;
        }
        public String getLrr() {
                return lrr;
        }
        public String getDjzclxmc() {
                return djzclxmc;
        }
        public Timestamp getCjrq() {
        return cjrq;
        }
        public String getSwjgzzjgdm2() {
                return swjgzzjgdm2;
        }
        public String getSbhzdh() {
                return sbhzdh;
        }
        public Timestamp getLrrq() {
        return lrrq;
        }
        public String getDz() {
                return dz;
        }
        public String getFsdm() {
                return fsdm;
        }
        public String getZjlxdm() {
                return zjlxdm;
        }
        public String getWszh() {
                return wszh;
        }
        public String getPzzldm() {
                return pzzldm;
        }
        public String getClbjdm() {
                return clbjdm;
        }
        public BigDecimal getHjsjje() {
                return hjsjje;
        }
        public String getJbdh() {
                return jbdh;
        }
        public String getSwjgzzjgdm() {
                return swjgzzjgdm;
        }
        public String getZjhm() {
                return zjhm;
        }
        public String getJsjdm() {
                return jsjdm;
        }
        public String getDjzclxdm() {
                return djzclxdm;
        }
        public String getGjbzhydm() {
                return gjbzhydm;
        }
        public String getNsrjsjdm() {
            return nsrjsjdm;
        }

        public void setSwjgzzjgmc( String _swjgzzjgmc ) {
                swjgzzjgmc = _swjgzzjgmc;
        }
        public void setLrr( String _lrr ) {
                lrr = _lrr;
        }
        public void setDjzclxmc( String _djzclxmc ) {
                djzclxmc = _djzclxmc;
        }
        public void setCjrq(Timestamp cjrq) {
            this.cjrq = cjrq;
        }
        public void setSwjgzzjgdm2( String _swjgzzjgdm2 ) {
                swjgzzjgdm2 = _swjgzzjgdm2;
        }
        public void setSbhzdh( String _sbhzdh ) {
                sbhzdh = _sbhzdh;
        }
        public void setLrrq(Timestamp lrrq) {
            this.lrrq = lrrq;
        }
        public void setDz( String _dz ) {
                dz = _dz;
        }
        public void setFsdm( String _fsdm ) {
                fsdm = _fsdm;
        }
        public void setZjlxdm( String _zjlxdm ) {
                zjlxdm = _zjlxdm;
        }
        public void setWszh( String _wszh ) {
                wszh = _wszh;
        }
        public void setPzzldm( String _pzzldm ) {
                pzzldm = _pzzldm;
        }
        public void setClbjdm( String _clbjdm ) {
                clbjdm = _clbjdm;
        }
        public void setHjsjje( BigDecimal _hjsjje ) {
                hjsjje = _hjsjje;
        }
        public void setJbdh( String _jbdh ) {
                jbdh = _jbdh;
        }
        public void setSwjgzzjgdm( String _swjgzzjgdm ) {
                swjgzzjgdm = _swjgzzjgdm;
        }
        public void setZjhm( String _zjhm ) {
                zjhm = _zjhm;
        }
        public void setJsjdm( String _jsjdm ) {
                jsjdm = _jsjdm;
        }
        public void setDjzclxdm( String _djzclxdm ) {
                djzclxdm = _djzclxdm;
        }
        public void setGjbzhydm( String _gjbzhydm ) {
                gjbzhydm = _gjbzhydm;
        }

        public void setNsrjsjdm(String _nsrjsjdm)
        {
            nsrjsjdm = _nsrjsjdm;
        }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
  public String getWszxh() {
    return wszxh;
  }
  public void setWszxh(String wszxh) {
    this.wszxh = wszxh;
  }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }
    public String getNdzb()
    {
        return ndzb;
    }
    public void setNdzb(String ndzb)
    {
        this.ndzb = ndzb;
    }

}
