/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:06
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Gtgshyysrmx implements ORObject {

	String szsmmc;
	String jsjdm;
	BigDecimal dqkjfpje;
	Timestamp cjrq;
	BigDecimal jzyysr;
	BigDecimal dqwkjfpje;
	Timestamp sbrq;
	BigDecimal dqyysrjehj;
	String szsmdm;
        String swjgzzjgdm;
        String nd;
    private String qxdm;
  private java.sql.Timestamp lrrq;
	public Gtgshyysrmx () {}
	public String getSzsmmc() {
		return szsmmc;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public BigDecimal getDqkjfpje() {
		return dqkjfpje;
	}
	public Timestamp getCjrq() {
    return cjrq;
	}
	public BigDecimal getJzyysr() {
		return jzyysr;
	}
	public BigDecimal getDqwkjfpje() {
		return dqwkjfpje;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public BigDecimal getDqyysrjehj() {
		return dqyysrjehj;
	}
	public String getSzsmdm() {
		return szsmdm;
	}
	public void setSzsmmc( String _szsmmc ) {
		szsmmc = _szsmmc;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setDqkjfpje( BigDecimal _dqkjfpje ) {
		dqkjfpje = _dqkjfpje;
	}
	public void setCjrq(Timestamp cjrq) {
    this.cjrq = cjrq;
	}
	public void setJzyysr( BigDecimal _jzyysr ) {
		jzyysr = _jzyysr;
	}
	public void setDqwkjfpje( BigDecimal _dqwkjfpje ) {
		dqwkjfpje = _dqwkjfpje;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setDqyysrjehj( BigDecimal _dqyysrjehj ) {
		dqyysrjehj = _dqyysrjehj;
	}
	public void setSzsmdm( String _szsmdm ) {
		szsmdm = _szsmdm;
	}
  public String getSwjgzzjgdm() {
    return swjgzzjgdm;
  }
  public void setSwjgzzjgdm(String swjgzzjgdm) {
    this.swjgzzjgdm = swjgzzjgdm;
  }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }
  public java.sql.Timestamp getLrrq() {
    return lrrq;
  }
  public void setLrrq(java.sql.Timestamp lrrq) {
    this.lrrq = lrrq;
  }

}
