/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:07
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;

import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import java.sql.Timestamp;
import com.ekernel.db.or.ORObject;

/**
 * This is the entity / business object
 * We will use this business object to demonstrate OR Mapping in Kernl can
 * be used for composition.
 **/
public class Gtgshyysrz implements ORObject
{

    Timestamp lrrq;
    String lrrdm;
    String jsjdm;
    Timestamp cjrq;
    String swjgzzjgdm;
    Timestamp sbrq;
    String fsdm;
    String swdjzh;
    String nsrmc;
    Timestamp skssjsrq;
    Timestamp skssksrq;
    String nd;
    private String qxdm;
    public Gtgshyysrz()
    {}

    public Timestamp getLrrq()
    {
        return lrrq;
    }

    public String getLrrdm()
    {
        return lrrdm;
    }

    public String getJsjdm()
    {
        return jsjdm;
    }

    public Timestamp getCjrq()
    {
        return cjrq;
    }

    public String getSwjgzzjgdm()
    {
        return swjgzzjgdm;
    }

    public Timestamp getSbrq()
    {
        return sbrq;
    }

    public String getFsdm()
    {
        return fsdm;
    }

    public String getSwdjzh()
    {
        return swdjzh;
    }

    public String getNsrmc()
    {
        return nsrmc;
    }

    public Timestamp getSkssksrq()
    {
        return skssksrq;
    }

    public Timestamp getSkssjsrq()
    {
        return skssjsrq;
    }

    public void setLrrq(Timestamp _lrrq)
    {
        lrrq = _lrrq;
    }

    public void setLrrdm(String _lrrdm)
    {
        lrrdm = _lrrdm;
    }

    public void setJsjdm(String _jsjdm)
    {
        jsjdm = _jsjdm;
    }

    public void setCjrq(Timestamp cjrq)
    {
        this.cjrq = cjrq;
    }

    public void setSwjgzzjgdm(String _swjgzzjgdm)
    {
        swjgzzjgdm = _swjgzzjgdm;
    }

    public void setSbrq(Timestamp _sbrq)
    {
        sbrq = _sbrq;
    }

    public void setFsdm(String _fsdm)
    {
        fsdm = _fsdm;
    }

    public void setSwdjzh(String _swdjzh)
    {
        swdjzh = _swdjzh;
    }

    public void setNsrmc(String _nsrmc)
    {
        nsrmc = _nsrmc;
    }

    public void setSkssksrq(Timestamp _skssksrq)
    {
        skssksrq = _skssksrq;
    }

    public void setSkssjsrq(Timestamp _skssjsrq)
    {
        skssjsrq = _skssjsrq;
    }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }

}