/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:04
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Gtgshsdsz implements ORObject {

	String zh;
	Timestamp lrrq;
	Timestamp skssksrq;
	String jsjdm;
	String qyyb;
	String xm;
	String yhdm;
	Timestamp skssjsrq;
	Timestamp cjrq;
	String lxdh;
	String swjgzzjgdm;
	Timestamp sbrq;
	Timestamp scjyrq;
	String lrr;
	String fsdm;
	String dz;
	String nsrmc;
        String nd;
    private String qxdm;
	public Gtgshsdsz () {}
	public String getZh() {
		return zh;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public Timestamp getSkssksrq() {
		return skssksrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getQyyb() {
		return qyyb;
	}
	public String getXm() {
		return xm;
	}
	public String getYhdm() {
		return yhdm;
	}
	public Timestamp getSkssjsrq() {
		return skssjsrq;
	}
	public Timestamp getCjrq() {
        return cjrq;
	}
	public String getLxdh() {
		return lxdh;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public Timestamp getScjyrq() {
		return scjyrq;
	}
	public String getLrr() {
		return lrr;
	}
	public String getFsdm() {
		return fsdm;
	}
	public String getDz() {
		return dz;
	}
	public String getNsrmc() {
		return nsrmc;
	}
	public void setZh( String _zh ) {
		zh = _zh;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setSkssksrq( Timestamp _skssksrq ) {
		skssksrq = _skssksrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setQyyb( String _qyyb ) {
		qyyb = _qyyb;
	}
	public void setXm( String _xm ) {
		xm = _xm;
	}
	public void setYhdm( String _yhdm ) {
		yhdm = _yhdm;
	}
	public void setSkssjsrq( Timestamp _skssjsrq ) {
		skssjsrq = _skssjsrq;
	}
	public void setCjrq(Timestamp cjrq) {
//		cjsj = _cjsj;
        this.cjrq = cjrq;
	}
	public void setLxdh( String _lxdh ) {
		lxdh = _lxdh;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setScjyrq( Timestamp _scjyrq ) {
		scjyrq = _scjyrq;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
	public void setDz( String _dz ) {
		dz = _dz;
	}
	public void setNsrmc( String _nsrmc ) {
		nsrmc = _nsrmc;
	}
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }

}
