/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 31-Ê®¶þÔÂ-2004 10:23:21
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class GtgshZt implements ORObject {

	String yd;
	String lrr;
	long zjls;
	String yckkzt;
	double cwzje;
	String nd;
	String cjr;
	double zje;
	Timestamp lrrq;
	String eckkzt;
	long cwzjls;
	String dsczt;
	String eckknrzt;
	String yckknrzt;
	String yhqzt;
	String bz;
	Timestamp cjrq;
	String qxdm;
	String ydkkwjmc;
	public GtgshZt () {}
	public String getYd() {
		return yd;
	}
	public String getLrr() {
		return lrr;
	}
	public long getZjls() {
		return zjls;
	}
	public String getYckkzt() {
		return yckkzt;
	}
	public double getCwzje() {
		return cwzje;
	}
	public String getNd() {
		return nd;
	}
	public String getCjr() {
		return cjr;
	}
	public double getZje() {
		return zje;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getEckkzt() {
		return eckkzt;
	}
	public long getCwzjls() {
		return cwzjls;
	}
	public String getDsczt() {
		return dsczt;
	}
	public String getEckknrzt() {
		return eckknrzt;
	}
	public String getYckknrzt() {
		return yckknrzt;
	}
	public String getYhqzt() {
		return yhqzt;
	}
	public String getBz() {
		return bz;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getQxdm() {
		return qxdm;
	}
	public String getYdkkwjmc() {
		return ydkkwjmc;
	}
	public void setYd( String _yd ) {
		yd = _yd;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setZjls( long _zjls ) {
		zjls = _zjls;
	}
	public void setZjls( BigDecimal _zjls ) {
		zjls = _zjls.longValue();
	}
	public void setYckkzt( String _yckkzt ) {
		yckkzt = _yckkzt;
	}
	public void setCwzje( double _cwzje ) {
		cwzje = _cwzje;
	}
	public void setCwzje( BigDecimal _cwzje ) {
		cwzje = _cwzje.doubleValue();
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setZje( double _zje ) {
		zje = _zje;
	}
	public void setZje( BigDecimal _zje ) {
		zje = _zje.doubleValue();
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setEckkzt( String _eckkzt ) {
		eckkzt = _eckkzt;
	}
	public void setCwzjls( long _cwzjls ) {
		cwzjls = _cwzjls;
	}
	public void setCwzjls( BigDecimal _cwzjls ) {
		cwzjls = _cwzjls.longValue();
	}
	public void setDsczt( String _dsczt ) {
		dsczt = _dsczt;
	}
	public void setEckknrzt( String _eckknrzt ) {
		eckknrzt = _eckknrzt;
	}
	public void setYckknrzt( String _yckknrzt ) {
		yckknrzt = _yckknrzt;
	}
	public void setYhqzt( String _yhqzt ) {
		yhqzt = _yhqzt;
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public void setYdkkwjmc( String _ydkkwjmc ) {
		ydkkwjmc = _ydkkwjmc;
	}

}
