/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 09-ÈýÔÂ-2004 11:35:15
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Gzsxpl implements ORObject {

	String jsjdm;
	String ph;
	String yzbs;
	public Gzsxpl () {}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getPh() {
		return ph;
	}
	public String getYzbs() {
		return yzbs;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setPh( String _ph ) {
		ph = _ph;
	}
	public void setYzbs( String _yzbs ) {
		yzbs = _yzbs;
	}

}
