/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 15-ËÄÔÂ-2004 11:13:17
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Gzsx implements ORObject {

	Timestamp gzsxjsrq;
	String nsrmc;
	String lrr;
	Timestamp gzsxksrq;
	String swjgzzjgdm2;
	String gzsxnr;
	String lrrdm;
	String gzsxsdbz;
	Timestamp lrrq;
	Timestamp gzsxfcrq;
	String gzsxfcdw;
	String bz;
	String fzcbs;
	Timestamp cjrq;
	String swjgzzjgdm;
	String djzclxdm;
	String jsjdm;
	String ph;
	String qxdm;
	String gjbzhydm;
	String gzsx_id;
	String gzsxnrbt;
	public Gzsx () {}
	public Timestamp getGzsxjsrq() {
		return gzsxjsrq;
	}
	public String getNsrmc() {
		return nsrmc;
	}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getGzsxksrq() {
		return gzsxksrq;
	}
	public String getSwjgzzjgdm2() {
		return swjgzzjgdm2;
	}
	public String getGzsxnr() {
		return gzsxnr;
	}
	public String getLrrdm() {
		return lrrdm;
	}
	public String getGzsxsdbz() {
		return gzsxsdbz;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public Timestamp getGzsxfcrq() {
		return gzsxfcrq;
	}
	public String getGzsxfcdw() {
		return gzsxfcdw;
	}
	public String getBz() {
		return bz;
	}
	public String getFzcbs() {
		return fzcbs;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public String getDjzclxdm() {
		return djzclxdm;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getPh() {
		return ph;
	}
	public String getQxdm() {
		return qxdm;
	}
	public String getGjbzhydm() {
		return gjbzhydm;
	}
	public void setGzsxjsrq( Timestamp _gzsxjsrq ) {
		gzsxjsrq = _gzsxjsrq;
	}
	public void setNsrmc( String _nsrmc ) {
		nsrmc = _nsrmc;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setGzsxksrq( Timestamp _gzsxksrq ) {
		gzsxksrq = _gzsxksrq;
	}
	public void setSwjgzzjgdm2( String _swjgzzjgdm2 ) {
		swjgzzjgdm2 = _swjgzzjgdm2;
	}
	public void setGzsxnr( String _gzsxnr ) {
		gzsxnr = _gzsxnr;
	}
	public void setLrrdm( String _lrrdm ) {
		lrrdm = _lrrdm;
	}
	public void setGzsxsdbz( String _gzsxsdbz ) {
		gzsxsdbz = _gzsxsdbz;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setGzsxfcrq( Timestamp _gzsxfcrq ) {
		gzsxfcrq = _gzsxfcrq;
	}
	public void setGzsxfcdw( String _gzsxfcdw ) {
		gzsxfcdw = _gzsxfcdw;
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setFzcbs( String _fzcbs ) {
		fzcbs = _fzcbs;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setDjzclxdm( String _djzclxdm ) {
		djzclxdm = _djzclxdm;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setPh( String _ph ) {
		ph = _ph;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public void setGjbzhydm( String _gjbzhydm ) {
		gjbzhydm = _gjbzhydm;
	}
	public String getGzsx_id() {
		return gzsx_id;
	}
	public void setGzsx_id(String gzsx_id) {
		this.gzsx_id = gzsx_id;
	}
	public String getGzsxnrbt() {
		return gzsxnrbt;
	}
	public void setGzsxnrbt(String gzsxnrbt) {
		this.gzsxnrbt = gzsxnrbt;
	}

}
