/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:13
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Hdzstzzsb implements ORObject {

	BigDecimal jmse;
	BigDecimal qcwjsk;
	BigDecimal sjyjse;
	Timestamp cjsj;
	BigDecimal yjnse;
	String nd;
	BigDecimal ynssde;
	BigDecimal sskcs;
	Timestamp lrrq;
	String zjlxdm;
	Timestamp sbrq;
	String tzzxm;
	BigDecimal lrfpbl;
	BigDecimal ynse;
	String zjhm;
	String jsjdm;
	BigDecimal sysl;
	String jd;
        String swjgzzjgdm;
	public Hdzstzzsb () {}
	public BigDecimal getJmse() {
		return jmse;
	}
	public BigDecimal getQcwjsk() {
		return qcwjsk;
	}
	public BigDecimal getSjyjse() {
		return sjyjse;
	}
	public Timestamp getCjsj() {
		return cjsj;
	}
	public BigDecimal getYjnse() {
		return yjnse;
	}
	public String getNd() {
		return nd;
	}
	public BigDecimal getYnssde() {
		return ynssde;
	}
	public BigDecimal getSskcs() {
		return sskcs;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getZjlxdm() {
		return zjlxdm;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public String getTzzxm() {
		return tzzxm;
	}
	public BigDecimal getLrfpbl() {
		return lrfpbl;
	}
	public BigDecimal getYnse() {
		return ynse;
	}
	public String getZjhm() {
		return zjhm;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public BigDecimal getSysl() {
		return sysl;
	}
	public String getJd() {
		return jd;
	}

        public String getSwjgzzjgdm()
        {
            return swjgzzjgdm;
        }

	public void setJmse( BigDecimal _jmse ) {
		jmse = _jmse ;
	}
	public void setQcwjsk( BigDecimal _qcwjsk ) {
		qcwjsk = _qcwjsk ;
	}
	public void setSjyjse( BigDecimal _sjyjse ) {
		sjyjse = _sjyjse ;
	}
	public void setCjsj( Timestamp _cjsj ) {
		cjsj = _cjsj;
	}
	public void setYjnse( BigDecimal _yjnse ) {
		yjnse = _yjnse ;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setYnssde( BigDecimal _ynssde ) {
		ynssde = _ynssde ;
	}
	public void setSskcs( BigDecimal _sskcs ) {
		sskcs = _sskcs ;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setZjlxdm( String _zjlxdm ) {
		zjlxdm = _zjlxdm;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setTzzxm( String _tzzxm ) {
		tzzxm = _tzzxm;
	}
	public void setLrfpbl( BigDecimal _lrfpbl ) {
		lrfpbl = _lrfpbl ;
	}
	public void setYnse( BigDecimal _ynse ) {
		ynse = _ynse ;
	}
	public void setZjhm( String _zjhm ) {
		zjhm = _zjhm;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setSysl( BigDecimal _sysl ) {
		sysl = _sysl ;
	}
	public void setJd( String _jd ) {
		jd = _jd;
	}

        public void setSwjgzzjgdm(String _swjgzzjgdm)
        {
            swjgzzjgdm = _swjgzzjgdm;
        }

}
