/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:11
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Hdzsqysb implements ORObject {

	Timestamp lrrq;
	BigDecimal qysrze;
	Timestamp skssksrq;
	String jsjdm;
	String nd;
	Timestamp skssjsrq;
	Timestamp cjsj;
	String swjgzzjgdm;
	Timestamp sbrq;
	String jd;
	BigDecimal lrze;
	String lrr;
	String fsdm;
	String swdjzh;
	String nsrmc;
	BigDecimal yssdl;
	public Hdzsqysb () {}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public BigDecimal getQysrze() {
		return qysrze;
	}
	public Timestamp getSkssksrq() {
		return skssksrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getNd() {
		return nd;
	}
	public Timestamp getSkssjsrq() {
		return skssjsrq;
	}
	public Timestamp getCjsj() {
		return cjsj;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public String getJd() {
		return jd;
	}
	public BigDecimal getLrze() {
		return lrze;
	}
	public String getLrr() {
		return lrr;
	}
	public String getFsdm() {
		return fsdm;
	}
	public String getSwdjzh() {
		return swdjzh;
	}
	public String getNsrmc() {
		return nsrmc;
	}
	public BigDecimal getYssdl() {
		return yssdl;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setQysrze( BigDecimal _qysrze ) {
		qysrze = _qysrze ;
	}
	public void setSkssksrq( Timestamp _skssksrq ) {
		skssksrq = _skssksrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setSkssjsrq( Timestamp _skssjsrq ) {
		skssjsrq = _skssjsrq;
	}
	public void setCjsj( Timestamp _cjsj ) {
		cjsj = _cjsj;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setJd( String _jd ) {
		jd = _jd;
	}
	public void setLrze( BigDecimal _lrze ) {
		lrze = _lrze ;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
	public void setSwdjzh( String _swdjzh ) {
		swdjzh = _swdjzh;
	}
	public void setNsrmc( String _nsrmc ) {
		nsrmc = _nsrmc;
	}
	public void setYssdl( BigDecimal _yssdl ) {
		yssdl = _yssdl ;
	}

}
