/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:14
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Jjlxglszsm implements ORObject {

	String djzclxdm;
	String zqlxmc;
	String szsmdm;
	String zqlxdm;
	public Jjlxglszsm () {}
	public String getDjzclxdm() {
		return djzclxdm;
	}
	public String getZqlxmc() {
		return zqlxmc;
	}
	public String getSzsmdm() {
		return szsmdm;
	}
	public String getZqlxdm() {
		return zqlxdm;
	}
	public void setDjzclxdm( String _djzclxdm ) {
		djzclxdm = _djzclxdm;
	}
	public void setZqlxmc( String _zqlxmc ) {
		zqlxmc = _zqlxmc;
	}
	public void setSzsmdm( String _szsmdm ) {
		szsmdm = _szsmdm;
	}
	public void setZqlxdm( String _zqlxdm ) {
		zqlxdm = _zqlxdm;
	}

}
