/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:15
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Jm implements ORObject {

	Timestamp lrrq;
	BigDecimal jsje;
	String jmlx;
	String jsjdm;
	BigDecimal kssl;
	String jzbz;
	Timestamp cjrq;
	String swjgzzjgdm;
	BigDecimal jmse;
	Timestamp sbrq;
	String szsmdm;
	String lrr;
	String fsdm;
	String nsrmc;
    String jmxmdm;
    String djzclxdm;
    String gjbzhydm;
    String yskmdm;
    String ysjcdm;
    Timestamp skssjsrq;
    Timestamp skssksrq;
    String nd;
    String qxdm;
    BigDecimal dqxse;
    BigDecimal dqlrze;
    BigDecimal qyrs;
    BigDecimal azrs;
    BigDecimal azbl;
    String jmxmjdm;
    Timestamp jmxmksrq;
    Timestamp jmxmjsrq;
    String sjly;

	public Jm () {this.jzbz = "000000";}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public BigDecimal getJsje() {
		return jsje;
	}
	public String getJmlx() {
		return jmlx;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public BigDecimal getKssl() {
		return kssl;
	}
	public String getJzbz() {
		return jzbz;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public BigDecimal getJmse() {
		return jmse;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public String getSzsmdm() {
		return szsmdm;
	}
	public String getLrr() {
		return lrr;
	}
	public String getFsdm() {
		return fsdm;
	}
	public String getNsrmc() {
		return nsrmc;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setJsje( BigDecimal _jsje ) {
		jsje = _jsje ;
	}
	public void setJmlx( String _jmlx ) {
		jmlx = _jmlx;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setKssl( BigDecimal _kssl ) {
		kssl = _kssl ;
	}
	public void setJzbz( String _jzbz ) {
		jzbz = _jzbz;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setJmse( BigDecimal _jmse ) {
		jmse = _jmse ;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setSzsmdm( String _szsmdm ) {
		szsmdm = _szsmdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
	public void setNsrmc( String _nsrmc ) {
		nsrmc = _nsrmc;
	}
    public String getDjzclxdm()
    {
        return djzclxdm;
    }
    public void setDjzclxdm(String djzclxdm)
    {
        this.djzclxdm = djzclxdm;
    }
    public String getGjbzhydm()
    {
        return gjbzhydm;
    }
    public void setGjbzhydm(String gjbzhydm)
    {
        this.gjbzhydm = gjbzhydm;
    }
    public String getJmxmdm()
    {
        return jmxmdm;
    }
    public void setJmxmdm(String jmxmdm)
    {
        this.jmxmdm = jmxmdm;
    }
    public String getYsjcdm()
    {
        return ysjcdm;
    }
    public void setYsjcdm(String ysjcdm)
    {
        this.ysjcdm = ysjcdm;
    }
    public String getYskmdm()
    {
        return yskmdm;
    }
    public void setYskmdm(String yskmdm)
    {
        this.yskmdm = yskmdm;
    }
    public Timestamp getSkssjsrq()
    {
        return skssjsrq;
    }
    public void setSkssjsrq(Timestamp skssjsrq)
    {
        this.skssjsrq = skssjsrq;
    }
    public Timestamp getSkssksrq()
    {
        return skssksrq;
    }
    public void setSkssksrq(Timestamp skssksrq)
    {
        this.skssksrq = skssksrq;
    }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }

	public BigDecimal getDqxse() {
		return dqxse;
	}
	public void setDqxse(BigDecimal dqxse) {
		this.dqxse = dqxse;
	}
	public BigDecimal getDqlrze() {
		return dqlrze;
	}
	public void setDqlrze(BigDecimal dqlrze) {
		this.dqlrze = dqlrze;
	}
	public String getJmxmjdm() {
		return jmxmjdm;
	}
	public void setJmxmjdm(String jmxmjdm) {
		this.jmxmjdm = jmxmjdm;
	}
	
	public String getSjly() {
		return sjly;
	}
	public void setSjly(String sjly) {
		this.sjly = sjly;
	}
	public BigDecimal getAzbl() {
		return azbl;
	}
	public void setAzbl(BigDecimal azbl) {
		this.azbl = azbl;
	}
	public BigDecimal getQyrs() {
		return qyrs;
	}
	public void setQyrs(BigDecimal qyrs) {
		this.qyrs = qyrs;
	}
	public BigDecimal getAzrs() {
		return azrs;
	}
	public void setAzrs(BigDecimal azrs) {
		this.azrs = azrs;
	}
	public Timestamp getJmxmksrq() {
		return jmxmksrq;
	}
	public void setJmxmksrq(Timestamp jmxmksrq) {
		this.jmxmksrq = jmxmksrq;
	}
	public Timestamp getJmxmjsrq() {
		return jmxmjsrq;
	}
	public void setJmxmjsrq(Timestamp jmxmjsrq) {
		this.jmxmjsrq = jmxmjsrq;
	}

}
