/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-°ËÔÂ-2006 13:07:57
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class JMZC implements ORObject {

	Timestamp lrrq;
	String jmzczw;
	String sfyjyxbs;
	String jmzcdm;
	String zfbs;
	Timestamp yxqq;
	String jmzcmc;
	Timestamp cjrq;
	String cjr;
	String jmzcwh;
	String lrr;
	Timestamp yxqz;
	public JMZC () {}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getJmzczw() {
		return jmzczw;
	}
	public String getSfyjyxbs() {
		return sfyjyxbs;
	}
	public String getJmzcdm() {
		return jmzcdm;
	}
	public String getZfbs() {
		return zfbs;
	}
	public Timestamp getYxqq() {
		return yxqq;
	}
	public String getJmzcmc() {
		return jmzcmc;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getCjr() {
		return cjr;
	}
	public String getJmzcwh() {
		return jmzcwh;
	}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getYxqz() {
		return yxqz;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setJmzczw( String _jmzczw ) {
		jmzczw = _jmzczw;
	}
	public void setSfyjyxbs( String _sfyjyxbs ) {
		sfyjyxbs = _sfyjyxbs;
	}
	public void setJmzcdm( String _jmzcdm ) {
		jmzcdm = _jmzcdm;
	}
	public void setZfbs( String _zfbs ) {
		zfbs = _zfbs;
	}
	public void setYxqq( Timestamp _yxqq ) {
		yxqq = _yxqq;
	}
	public void setJmzcmc( String _jmzcmc ) {
		jmzcmc = _jmzcmc;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setJmzcwh( String _jmzcwh ) {
		jmzcwh = _jmzcwh;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setYxqz( Timestamp _yxqz ) {
		yxqz = _yxqz;
	}

}
