/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:17
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Jqsz implements ORObject {

	Timestamp jqrq;
	String ssnf;
  private java.sql.Timestamp cjrq;
  private java.sql.Timestamp lrrq;
  private String swjgzzjgdm;
	public Jqsz () {}
	public Timestamp getJqrq() {
		return jqrq;
	}
	public String getSsnf() {
		return ssnf;
	}
	public void setJqrq( Timestamp _jqrq ) {
		jqrq = _jqrq;
	}
	public void setSsnf( String _ssnf ) {
		ssnf = _ssnf;
	}
  public java.sql.Timestamp getCjrq() {
    return cjrq;
  }
  public void setCjrq(java.sql.Timestamp cjrq) {
    this.cjrq = cjrq;
  }
  public java.sql.Timestamp getLrrq() {
    return lrrq;
  }
  public void setLrrq(java.sql.Timestamp lrrq) {
    this.lrrq = lrrq;
  }
  public String getSwjgzzjgdm() {
    return swjgzzjgdm;
  }
  public void setSwjgzzjgdm(String swjgzzjgdm) {
    this.swjgzzjgdm = swjgzzjgdm;
  }

}
