/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 20-Ê®ÔÂ-2003 11:22:46
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Lsgx implements ORObject {

	String lrr;
	String lsgxmc;
	Timestamp zhgxsj;
	String zxbs;
	Timestamp lrrq;
	String lsgxdm;
	public Lsgx () {}
	public String getLrr() {
		return lrr;
	}
	public String getLsgxmc() {
		return lsgxmc;
	}
	public Timestamp getZhgxsj() {
		return zhgxsj;
	}
	public String getZxbs() {
		return zxbs;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getLsgxdm() {
		return lsgxdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setLsgxmc( String _lsgxmc ) {
		lsgxmc = _lsgxmc;
	}
	public void setZhgxsj( Timestamp _zhgxsj ) {
		zhgxsj = _zhgxsj;
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setLsgxdm( String _lsgxdm ) {
		lsgxdm = _lsgxdm;
	}

}
