/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:21
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Lswszsbhz implements ORObject {

	Timestamp hzjsrq;
	String jkpzh;
	String jsjdm;
	String swjgzzjgdm;
	BigDecimal sjse;
	Timestamp hzrq;
	Timestamp hzksrq;
	String sbhzdh;
	String lrr;
	String clbjdm;
        String hzfs;
        String nd;
    private java.sql.Timestamp cjrq;
    private java.sql.Timestamp lrrq;
    private String qxdm;
	public Lswszsbhz () {}
	public Timestamp getHzjsrq() {
		return hzjsrq;
	}
	public String getJkpzh() {
		return jkpzh;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public BigDecimal getSjse() {
		return sjse;
	}
	public Timestamp getHzrq() {
		return hzrq;
	}
	public Timestamp getHzksrq() {
		return hzksrq;
	}
	public String getSbhzdh() {
		return sbhzdh;
	}
	public String getLrr() {
		return lrr;
	}
	public String getClbjdm() {
		return clbjdm;
	}

        public String getHzfs()
        {
            return hzfs;
        }

	public void setHzjsrq( Timestamp _hzjsrq ) {
		hzjsrq = _hzjsrq;
	}
	public void setJkpzh( String _jkpzh ) {
		jkpzh = _jkpzh;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setSjse( BigDecimal _sjse ) {
		sjse = _sjse;
	}
	public void setHzrq( Timestamp _hzrq ) {
		hzrq = _hzrq;
	}
	public void setHzksrq( Timestamp _hzksrq ) {
		hzksrq = _hzksrq;
	}
	public void setSbhzdh( String _sbhzdh ) {
		sbhzdh = _sbhzdh;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setClbjdm( String _clbjdm ) {
		clbjdm = _clbjdm;
	}

        public void setHzfs(String _hzfs)
        {
            hzfs = _hzfs;
        }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
    public java.sql.Timestamp getCjrq()
    {
        return cjrq;
    }
    public void setCjrq(java.sql.Timestamp cjrq)
    {
        this.cjrq = cjrq;
    }
    public java.sql.Timestamp getLrrq()
    {
        return lrrq;
    }
    public void setLrrq(java.sql.Timestamp lrrq)
    {
        this.lrrq = lrrq;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }

}
