/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 02-¾ÅÔÂ-2003 13:51:31
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Lswszz implements ORObject {

	String nsrmc;
	String swjgzzjgmc;
	String lrr;
	String djzclxmc;
	Timestamp cjsj;
	String swjgzzjgdm2;
	String sbhzdh;
	Timestamp krrq;
	String dz;
	String zjlxdm;
	String wszh;
	String pzzldm;
	String clbjdm;
	double hjsjje;
	String jbdh;
	String swjgzzjgdm;
	String djzclxdm;
	String jsjdm;
	String zjhm;
	public Lswszz () {}
	public String getNsrmc() {
		return nsrmc;
	}
	public String getSwjgzzjgmc() {
		return swjgzzjgmc;
	}
	public String getLrr() {
		return lrr;
	}
	public String getDjzclxmc() {
		return djzclxmc;
	}
	public Timestamp getCjsj() {
		return cjsj;
	}
	public String getSwjgzzjgdm2() {
		return swjgzzjgdm2;
	}
	public String getSbhzdh() {
		return sbhzdh;
	}
	public Timestamp getKrrq() {
		return krrq;
	}
	public String getDz() {
		return dz;
	}
	public String getZjlxdm() {
		return zjlxdm;
	}
	public String getWszh() {
		return wszh;
	}
	public String getPzzldm() {
		return pzzldm;
	}
	public String getClbjdm() {
		return clbjdm;
	}
	public double getHjsjje() {
		return hjsjje;
	}
	public String getJbdh() {
		return jbdh;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public String getDjzclxdm() {
		return djzclxdm;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getZjhm() {
		return zjhm;
	}
	public void setNsrmc( String _nsrmc ) {
		nsrmc = _nsrmc;
	}
	public void setSwjgzzjgmc( String _swjgzzjgmc ) {
		swjgzzjgmc = _swjgzzjgmc;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setDjzclxmc( String _djzclxmc ) {
		djzclxmc = _djzclxmc;
	}
	public void setCjsj( Timestamp _cjsj ) {
		cjsj = _cjsj;
	}
	public void setSwjgzzjgdm2( String _swjgzzjgdm2 ) {
		swjgzzjgdm2 = _swjgzzjgdm2;
	}
	public void setSbhzdh( String _sbhzdh ) {
		sbhzdh = _sbhzdh;
	}
	public void setKrrq( Timestamp _krrq ) {
		krrq = _krrq;
	}
	public void setDz( String _dz ) {
		dz = _dz;
	}
	public void setZjlxdm( String _zjlxdm ) {
		zjlxdm = _zjlxdm;
	}
	public void setWszh( String _wszh ) {
		wszh = _wszh;
	}
	public void setPzzldm( String _pzzldm ) {
		pzzldm = _pzzldm;
	}
	public void setClbjdm( String _clbjdm ) {
		clbjdm = _clbjdm;
	}
	public void setHjsjje( double _hjsjje ) {
		hjsjje = _hjsjje;
	}
	public void setHjsjje( BigDecimal _hjsjje ) {
		hjsjje = _hjsjje.doubleValue();
	}
	public void setJbdh( String _jbdh ) {
		jbdh = _jbdh;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setDjzclxdm( String _djzclxdm ) {
		djzclxdm = _djzclxdm;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setZjhm( String _zjhm ) {
		zjhm = _zjhm;
	}

}
