/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:22
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Lygf implements ORObject {

	Timestamp skssksrq;
	String nsrmc;
	String lrr;
	BigDecimal ynsdse;
	Timestamp cjrq;
	String nd;
	BigDecimal lr;
	BigDecimal ynssde;
	String fl;
	String fsdm;
	Timestamp lrrq;
	BigDecimal xh;
	String dwmc;
	Timestamp sbrq;
	BigDecimal ybsdse;
	String qylxdh;
	BigDecimal sskce;
	BigDecimal sl;
	String swjgzzjgdm;
	String jsjdm;
	Timestamp skssjsrq;
    String qxdm;

	public Lygf () {}
	public Timestamp getSkssksrq() {
		return skssksrq;
	}
	public String getNsrmc() {
		return nsrmc;
	}
	public String getLrr() {
		return lrr;
	}
	public BigDecimal getYnsdse() {
		return ynsdse;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getNd() {
		return nd;
	}
	public BigDecimal getLr() {
		return lr;
	}
	public BigDecimal getYnssde() {
		return ynssde;
	}
	public String getFl() {
		return fl;
	}
	public String getFsdm() {
		return fsdm;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public BigDecimal getXh() {
		return xh;
	}
	public String getDwmc() {
		return dwmc;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public BigDecimal getYbsdse() {
		return ybsdse;
	}
	public String getQylxdh() {
		return qylxdh;
	}
	public BigDecimal getSskce() {
		return sskce;
	}
	public BigDecimal getSl() {
		return sl;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public Timestamp getSkssjsrq() {
		return skssjsrq;
	}
	public void setSkssksrq( Timestamp _skssksrq ) {
		skssksrq = _skssksrq;
	}
	public void setNsrmc( String _nsrmc ) {
		nsrmc = _nsrmc;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setYnsdse( BigDecimal _ynsdse ) {
		ynsdse = _ynsdse ;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setLr( BigDecimal _lr ) {
		lr = _lr ;
	}
	public void setYnssde( BigDecimal _ynssde ) {
		ynssde = _ynssde ;
	}
	public void setFl( String _fl ) {
		fl = _fl;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setXh( BigDecimal _xh ) {
		xh = _xh;
	}
	public void setDwmc( String _dwmc ) {
		dwmc = _dwmc;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setYbsdse( BigDecimal _ybsdse ) {
		ybsdse = _ybsdse ;
	}
	public void setQylxdh( String _qylxdh ) {
		qylxdh = _qylxdh;
	}
	public void setSskce( BigDecimal _sskce ) {
		sskce = _sskce ;
	}
	public void setSl( BigDecimal _sl ) {
		sl = _sl ;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setSkssjsrq( Timestamp _skssjsrq ) {
		skssjsrq = _skssjsrq;
	}
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }

}
