/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:26
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.math.BigDecimal;
import java.sql.Timestamp;

import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Qysdsks implements ORObject {

	Timestamp lrrq;
	Timestamp skssksrq;
	String jsjdm;
	BigDecimal ynssde;
	BigDecimal yjnse;
	String nd;
	Timestamp skssjsrq;
	Timestamp cjsj;
	String swjgzzjgdm;
	Timestamp sbrq;
	String jd;
	String lrr;
	String fsdm;
	String nsrmc;
	public Qysdsks () {}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public Timestamp getSkssksrq() {
		return skssksrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public BigDecimal getYnssde() {
		return ynssde;
	}
	public BigDecimal getYjnse() {
		return yjnse;
	}
	public String getNd() {
		return nd;
	}
	public Timestamp getSkssjsrq() {
		return skssjsrq;
	}
	public Timestamp getCjsj() {
		return cjsj;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public String getJd() {
		return jd;
	}
	public String getLrr() {
		return lrr;
	}
	public String getFsdm() {
		return fsdm;
	}
	public String getNsrmc() {
		return nsrmc;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setSkssksrq( Timestamp _skssksrq ) {
		skssksrq = _skssksrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setYnssde( BigDecimal _ynssde ) {
		ynssde = _ynssde ;
	}
	public void setYjnse( BigDecimal _yjnse ) {
		yjnse = _yjnse ;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setSkssjsrq( Timestamp _skssjsrq ) {
		skssjsrq = _skssjsrq;
	}
	public void setCjsj( Timestamp _cjsj ) {
		cjsj = _cjsj;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setJd( String _jd ) {
		jd = _jd;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
	public void setNsrmc( String _nsrmc ) {
		nsrmc = _nsrmc;
	}

}
