/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:27
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Qysdsnb implements ORObject {

	Timestamp skssksrq;
	String zgswjgzzjgdm;
	String lrr;
	String dljgjsjdm;
	String dljgdwmc;
	Timestamp cjrq;
	String hc;
	String nd;
	String fsdm;
	Timestamp lrrq;
	BigDecimal bqljs;
	Timestamp sbrq;
	String swjgzzjgdm;
	String jsjdm;
	Timestamp skssjsrq;
    String qxdm;
	public Qysdsnb () {}
	public Timestamp getSkssksrq() {
		return skssksrq;
	}
	public String getZgswjgzzjgdm() {
		return zgswjgzzjgdm;
	}
	public String getLrr() {
		return lrr;
	}
	public String getDljgjsjdm() {
		return dljgjsjdm;
	}
	public String getDljgdwmc() {
		return dljgdwmc;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getHc() {
		return hc;
	}
	public String getNd() {
		return nd;
	}
	public String getFsdm() {
		return fsdm;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public BigDecimal getBqljs() {
		return bqljs;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public Timestamp getSkssjsrq() {
		return skssjsrq;
	}
	public void setSkssksrq( Timestamp _skssksrq ) {
		skssksrq = _skssksrq;
	}
	public void setZgswjgzzjgdm( String _zgswjgzzjgdm ) {
		zgswjgzzjgdm = _zgswjgzzjgdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setDljgjsjdm( String _dljgjsjdm ) {
		dljgjsjdm = _dljgjsjdm;
	}
	public void setDljgdwmc( String _dljgdwmc ) {
		dljgdwmc = _dljgdwmc;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setHc( String _hc ) {
		hc = _hc;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setBqljs( BigDecimal _bqljs ) {
		bqljs = _bqljs ;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setSkssjsrq( Timestamp _skssjsrq ) {
		skssjsrq = _skssjsrq;
	}
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }

}
