/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:35:24
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Sbbbxm implements ORObject {

	String xmmc;
	String sjkj;
	String sjly;
	String xmss;
	BigDecimal fbxh;
	String bjxz;
	String hc;
	String jytj;
	String sfjybs;
	public Sbbbxm () {}
	public String getXmmc() {
		return xmmc;
	}
	public String getSjkj() {
		return sjkj;
	}
	public String getSjly() {
		return sjly;
	}
	public String getXmss() {
		return xmss;
	}
	public BigDecimal getFbxh() {
		return fbxh;
	}
	public String getBjxz() {
		return bjxz;
	}
	public String getHc() {
		return hc;
	}
	public String getJytj() {
		return jytj;
	}
	public String getSfjybs() {
		return sfjybs;
	}
	public void setXmmc( String _xmmc ) {
		xmmc = _xmmc;
	}
	public void setSjkj( String _sjkj ) {
		sjkj = _sjkj;
	}
	public void setSjly( String _sjly ) {
		sjly = _sjly;
	}
	public void setXmss( String _xmss ) {
		xmss = _xmss;
	}
	public void setFbxh( BigDecimal _fbxh ) {
		fbxh = _fbxh;
	}
	public void setBjxz( String _bjxz ) {
		bjxz = _bjxz;
	}
	public void setHc( String _hc ) {
		hc = _hc;
	}
	public void setJytj( String _jytj ) {
		jytj = _jytj;
	}
	public void setSfjybs( String _sfjybs ) {
		sfjybs = _sfjybs;
	}

}
