/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:28
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Sbbxmdzb implements ORObject {

	String xmss;
	BigDecimal xh;
	String xmmc;
	String xmdm;
	public Sbbxmdzb () {}
	public String getXmss() {
		return xmss;
	}
	public BigDecimal getXh() {
		return xh;
	}
	public String getXmmc() {
		return xmmc;
	}
	public String getXmdm() {
		return xmdm;
	}
	public void setXmss( String _xmss ) {
		xmss = _xmss;
	}
	public void setXh( BigDecimal _xh ) {
		xh = _xh;
	}
	public void setXmmc( String _xmmc ) {
		xmmc = _xmmc;
	}
	public void setXmdm( String _xmdm ) {
		xmdm = _xmdm;
	}

}
