/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:33
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;

import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
 * This is the entity / business object
 * We will use this business object to demonstrate OR Mapping in Kernl can
 * be used for composition.
 **/
public class Sdwszsbhz implements ORObject
{

    Timestamp hzjsrq;
    String sjly;
    String jkpzh;
    String jsjdm;
    String swjgzzjgdm;
    BigDecimal sjse;
    String sbhzdh;
    Timestamp hzrq;
    Timestamp hzksrq;
    String lrr;
    String clbjdm;
    String sbbh;
    String nd;

    Timestamp lrrq;
    Timestamp cjrq;
    String qxdm;

    public Sdwszsbhz() {  }

    public Timestamp getHzjsrq()
    {
        return hzjsrq;
    }

    public String getSjly()
    {
        return sjly;
    }

    public String getJkpzh()
    {
        return jkpzh;
    }

    public String getJsjdm()
    {
        return jsjdm;
    }

    public String getSwjgzzjgdm()
    {
        return swjgzzjgdm;
    }

    public BigDecimal getSjse()
    {
        return sjse;
    }

    public String getSbhzdh()
    {
        return sbhzdh;
    }

    public Timestamp getHzrq()
    {
        return hzrq;
    }

    public Timestamp getHzksrq()
    {
        return hzksrq;
    }

    public String getLrr()
    {
        return lrr;
    }

    public String getClbjdm()
    {
        return clbjdm;
    }

    public void setHzjsrq(Timestamp _hzjsrq)
    {
        hzjsrq = _hzjsrq;
    }

    public void setSjly(String _sjly)
    {
        sjly = _sjly;
    }

    public void setJkpzh(String _jkpzh)
    {
        jkpzh = _jkpzh;
    }

    public void setJsjdm(String _jsjdm)
    {
        jsjdm = _jsjdm;
    }

    public void setSwjgzzjgdm(String _swjgzzjgdm)
    {
        swjgzzjgdm = _swjgzzjgdm;
    }

    public void setSjse(BigDecimal _sjse)
    {
        sjse = _sjse;
    }

    public void setSbhzdh(String _sbhzdh)
    {
        sbhzdh = _sbhzdh;
    }

    public void setHzrq(Timestamp _hzrq)
    {
        hzrq = _hzrq;
    }

    public void setHzksrq(Timestamp _hzksrq)
    {
        hzksrq = _hzksrq;
    }

    public void setLrr(String _lrr)
    {
        lrr = _lrr;
    }

    public void setClbjdm(String _clbjdm)
    {
        clbjdm = _clbjdm;
    }

    public String getSbbh()
    {
        return sbbh;
    }

    public void setSbbh(String sbbh)
    {
        this.sbbh = sbbh;
    }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
    public Timestamp getCjrq()
    {
        return cjrq;
    }
    public void setCjrq(Timestamp cjrq)
    {
        this.cjrq = cjrq;
    }
    public Timestamp getLrrq()
    {
        return lrrq;
    }
    public void setLrrq(Timestamp lrrq)
    {
        this.lrrq = lrrq;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }

}