/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-Ê®Ò»ÔÂ-2003 20:20:33
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Sklx implements ORObject {

	String lrr;
	String sbsybs;
	String sklxdm;
	String ccbs;
	String lrxsbs;
	String zxbs;
	Timestamp lrrq;
	String sklxmc;
	public Sklx () {}
	public String getLrr() {
		return lrr;
	}
	public String getSbsybs() {
		return sbsybs;
	}
	public String getSklxdm() {
		return sklxdm;
	}
	public String getCcbs() {
		return ccbs;
	}
	public String getLrxsbs() {
		return lrxsbs;
	}
	public String getZxbs() {
		return zxbs;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getSklxmc() {
		return sklxmc;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setSbsybs( String _sbsybs ) {
		sbsybs = _sbsybs;
	}
	public void setSklxdm( String _sklxdm ) {
		sklxdm = _sklxdm;
	}
	public void setCcbs( String _ccbs ) {
		ccbs = _ccbs;
	}
	public void setLrxsbs( String _lrxsbs ) {
		lrxsbs = _lrxsbs;
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setSklxmc( String _sklxmc ) {
		sklxmc = _sklxmc;
	}

}
