/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:35
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Sqsbtmp implements ORObject {

	String szmc;
	String szsmmc;
	BigDecimal kssl;
	String jsjdm;
	BigDecimal jsje;
	String szsmdm;
	String szdm;
	BigDecimal sjse;
    String qxdm;
    String swjgzzjgdm;
    Timestamp cjrq;
    Timestamp lrrq;

	public Sqsbtmp () {}
	public String getSzmc() {
		return szmc;
	}
	public String getSzsmmc() {
		return szsmmc;
	}
	public BigDecimal getKssl() {
		return kssl;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public BigDecimal getJsje() {
		return jsje;
	}
	public String getSzsmdm() {
		return szsmdm;
	}
	public String getSzdm() {
		return szdm;
	}
	public BigDecimal getSjse() {
		return sjse;
	}
	public void setSzmc( String _szmc ) {
		szmc = _szmc;
	}
	public void setSzsmmc( String _szsmmc ) {
		szsmmc = _szsmmc;
	}
	public void setKssl( BigDecimal _kssl ) {
		kssl = _kssl ;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setJsje( BigDecimal _jsje ) {
		jsje = _jsje ;
	}
	public void setSzsmdm( String _szsmdm ) {
		szsmdm = _szsmdm;
	}
	public void setSzdm( String _szdm ) {
		szdm = _szdm;
	}
	public void setSjse( BigDecimal _sjse ) {
		sjse = _sjse ;
	}
    public Timestamp getCjrq()
    {
        return cjrq;
    }
    public void setCjrq(Timestamp cjrq)
    {
        this.cjrq = cjrq;
    }
    public Timestamp getLrrq()
    {
        return lrrq;
    }
    public void setLrrq(Timestamp lrrq)
    {
        this.lrrq = lrrq;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }
    public String getSwjgzzjgdm()
    {
        return swjgzzjgdm;
    }
    public void setSwjgzzjgdm(String swjgzzjgdm)
    {
        this.swjgzzjgdm = swjgzzjgdm;
    }

}
