/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:41
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Szsmyfjs implements ORObject {

	String fjsszsmdm;
	String szsmdm;
	public Szsmyfjs () {}
	public String getFjsszsmdm() {
		return fjsszsmdm;
	}
	public String getSzsmdm() {
		return szsmdm;
	}
	public void setFjsszsmdm( String _fjsszsmdm ) {
		fjsszsmdm = _fjsszsmdm;
	}
	public void setSzsmdm( String _szsmdm ) {
		szsmdm = _szsmdm;
	}

}
