/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:35:30
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Szsm implements ORObject {

    public Szsm replicate()
    {
        Szsm szsm = new Szsm();
        szsm.setSzsmdm(this.szsmdm);
        szsm.setSzsmmc(this.szsmmc);
        szsm.setZqlxdm(this.zqlxdm);
        szsm.setFjddm(this.fjddm);
        szsm.setCcbs(this.ccbs);

        return szsm;
    }

    String jsgs;
    Timestamp zxksrq;
    String jldw;
    BigDecimal jsjs;
    BigDecimal bhsdskcs;
    BigDecimal ynsqss;
    String pysy;
    String sffjs;
    String zdkbjbz;
    String asljbs;
    BigDecimal ynszzs;
    BigDecimal sskcs;
    String szsmdm;
    BigDecimal bhsdssl;
    String bz;
    BigDecimal bhsdszz;
    String szsmmc;
    BigDecimal sl;
    Timestamp zxjsrq;
    BigDecimal bhsdsqs;
    String zqlxdm;
    String sjlyzd;
    BigDecimal jfys;
    String fjddm;
    String zxbs;
    String ccbs;

    public Szsm () {}
    public String getFjddm()  {
        return fjddm;
    }
    public String getJsgs() {
        return jsgs;
    }
    public Timestamp getZxksrq() {
        return zxksrq;
    }
    public String getJldw() {
        return jldw;
    }
    public BigDecimal getJsjs() {
        return jsjs;
    }
    public BigDecimal getBhsdskcs() {
        return bhsdskcs;
    }
    public BigDecimal getYnsqss() {
        return ynsqss;
    }
    public String getPysy() {
        return pysy;
    }
    public String getSffjs() {
        return sffjs;
    }
    public String getZdkbjbz() {
        return zdkbjbz;
    }
    public String getAsljbs() {
        return asljbs;
    }
    public BigDecimal getYnszzs() {
        return ynszzs;
    }
    public BigDecimal getSskcs() {
        return sskcs;
    }
    public String getSzsmdm() {
        return szsmdm;
    }
    public BigDecimal getBhsdssl() {
        return bhsdssl;
    }
    public String getBz() {
        return bz;
    }
    public BigDecimal getBhsdszz() {
        return bhsdszz;
    }
    public String getSzsmmc() {
        return szsmmc;
    }
    public BigDecimal getSl() {
        return sl;
    }
    public Timestamp getZxjsrq() {
        return zxjsrq;
    }
    public BigDecimal getBhsdsqs() {
        return bhsdsqs;
    }
    public String getZqlxdm() {
        return zqlxdm;
    }
    public String getSjlyzd() {
        return sjlyzd;
    }
    public BigDecimal getJfys() {
        return jfys;
    }
    public void setFjddm( String _fjddm )  {
        fjddm = _fjddm;
    }
    public void setJsgs( String _jsgs ) {
        jsgs = _jsgs;
    }
    public void setZxksrq( Timestamp _zxksrq ) {
        zxksrq = _zxksrq;
    }
    public void setJldw( String _jldw ) {
        jldw = _jldw;
    }
    public void setJsjs( BigDecimal _jsjs ) {
        jsjs = _jsjs;
    }
    public void setBhsdskcs( BigDecimal _bhsdskcs ) {
        bhsdskcs = _bhsdskcs;
    }
    public void setYnsqss( BigDecimal _ynsqss ) {
        ynsqss = _ynsqss;
    }
    public void setPysy( String _pysy ) {
        pysy = _pysy;
    }
    public void setSffjs( String _sffjs ) {
        sffjs = _sffjs;
    }
    public void setZdkbjbz( String _zdkbjbz ) {
        zdkbjbz = _zdkbjbz;
    }
    public void setAsljbs( String _asljbs ) {
        asljbs = _asljbs;
    }
    public void setYnszzs( BigDecimal _ynszzs ) {
        ynszzs = _ynszzs;
    }
    public void setSskcs( BigDecimal _sskcs ) {
        sskcs = _sskcs;
    }
    public void setSzsmdm( String _szsmdm ) {
        szsmdm = _szsmdm;
    }
    public void setBhsdssl( BigDecimal _bhsdssl ) {
        bhsdssl = _bhsdssl;
    }
    public void setBz( String _bz ) {
        bz = _bz;
    }
    public void setBhsdszz( BigDecimal _bhsdszz ) {
        bhsdszz = _bhsdszz;
    }
    public void setSzsmmc( String _szsmmc ) {
        szsmmc = _szsmmc;
    }
    public void setSl( BigDecimal _sl ) {
        sl = _sl;
    }
    public void setZxjsrq( Timestamp _zxjsrq ) {
        zxjsrq = _zxjsrq;
    }
    public void setBhsdsqs( BigDecimal _bhsdsqs ) {
        bhsdsqs = _bhsdsqs;
    }
    public void setZqlxdm( String _zqlxdm ) {
        zqlxdm = _zqlxdm;
    }
    public void setSjlyzd( String _sjlyzd ) {
        sjlyzd = _sjlyzd;
    }
    public void setJfys( BigDecimal _jfys ) {
        jfys = _jfys;
    }
    public String getZxbs()  {
        return zxbs;
    }
    public void setZxbs(String _zxbs)  {
        zxbs = _zxbs;
    }
    public String getCcbs()
    {
        return ccbs;
    }
    public void setCcbs(String ccbs)
    {
        this.ccbs = ccbs;
    }
}
