/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:35:32
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Wbhs implements ORObject {

    BigDecimal je;
    String bzdm;
    long xh;
    BigDecimal whpj;
    BigDecimal zhrmb;
    String bzmc;
    String yf;
    String nd;
    public Wbhs () {}
    public BigDecimal getJe() {
        return je;
    }
    public String getBzdm() {
        return bzdm;
    }
    public long getXh() {
        return xh;
    }
    public BigDecimal getWhpj() {
        return whpj;
    }
    public BigDecimal getZhrmb() {
        return zhrmb;
    }
    public String getBzmc() {
        return bzmc;
    }
    public String getYf() {
        return yf;
    }
    public String getNd() {
        return nd;
    }
    public void setJe( BigDecimal _je ) {
        je = _je;
    }
    public void setBzdm( String _bzdm ) {
        bzdm = _bzdm;
    }
    public void setXh( long _xh ) {
        xh = _xh;
    }
    public void setXh( BigDecimal _xh ) {
        xh = _xh.longValue();
    }
    public void setWhpj( BigDecimal _whpj ) {
        whpj = _whpj;
    }
    public void setZhrmb( BigDecimal _zhrmb ) {
        zhrmb = _zhrmb;
    }
    public void setBzmc( String _bzmc ) {
        bzmc = _bzmc;
    }
    public void setYf( String _yf ) {
        yf = _yf;
    }
    public void setNd( String _nd ) {
        nd = _nd;
    }
}
