/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 20-Ê®Ò»ÔÂ-2003 14:49:39
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;

import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
 * This is the entity / business object
 * We will use this business object to demonstrate OR Mapping in Kernl can
 * be used for composition.
 **/
public class Wbzhrmb implements ORObject
{
    String sbbh;
    String qxdm;
    Timestamp sdksrq;
    String jsjdm;
    Timestamp sdjsrq;
    String bzdm;
    Timestamp cjrq;
    String swjgzzjgdm;
    BigDecimal je;
    Timestamp sbrq;
    String szsmdm;
    BigDecimal zhrmb;
    BigDecimal whpj;
    Timestamp lrrq;
    public Wbzhrmb()
    {}

    public String getQxdm()
    {
        return qxdm;
    }

    public Timestamp getSdksrq()
    {
        return sdksrq;
    }

    public String getJsjdm()
    {
        return jsjdm;
    }

    public Timestamp getSdjsrq()
    {
        return sdjsrq;
    }

    public String getBzdm()
    {
        return bzdm;
    }

    public Timestamp getCjrq()
    {
        return cjrq;
    }

    public String getSwjgzzjgdm()
    {
        return swjgzzjgdm;
    }

    public BigDecimal getJe()
    {
        return je;
    }

    public Timestamp getSbrq()
    {
        return sbrq;
    }

    public String getSzsmdm()
    {
        return szsmdm;
    }

    public BigDecimal getZhrmb()
    {
        return zhrmb;
    }

    public BigDecimal getWhpj()
    {
        return whpj;
    }

    public Timestamp getLrrq()
    {
        return lrrq;
    }

    public void setQxdm(String _qxdm)
    {
        qxdm = _qxdm;
    }

    public void setSdksrq(Timestamp _sdksrq)
    {
        sdksrq = _sdksrq;
    }

    public void setJsjdm(String _jsjdm)
    {
        jsjdm = _jsjdm;
    }

    public void setSdjsrq(Timestamp _sdjsrq)
    {
        sdjsrq = _sdjsrq;
    }

    public void setBzdm(String _bzdm)
    {
        bzdm = _bzdm;
    }

    public void setCjrq(Timestamp _cjrq)
    {
        cjrq = _cjrq;
    }

    public void setSwjgzzjgdm(String _swjgzzjgdm)
    {
        swjgzzjgdm = _swjgzzjgdm;
    }

    public void setJe(BigDecimal _je)
    {
        je = _je;
    }

    public void setSbrq(Timestamp _sbrq)
    {
        sbrq = _sbrq;
    }

    public void setSzsmdm(String _szsmdm)
    {
        szsmdm = _szsmdm;
    }

    public void setZhrmb(BigDecimal _zhrmb)
    {
        zhrmb = _zhrmb;
    }

    public void setWhpj(BigDecimal _whpj)
    {
        whpj = _whpj;
    }

    public void setLrrq(Timestamp _lrrq)
    {
        lrrq = _lrrq;
    }

    public String getSbbh()
    {
        return sbbh;
    }

    public void setSbbh(String sbbh)
    {
        this.sbbh = sbbh;
    }
}