/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:45
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Wqyys implements ORObject {

        Timestamp skssksrq;
        String nsrmc;
        String lrr;
        BigDecimal htcje;
        BigDecimal yinse;
        BigDecimal sre;
        Timestamp cjrq;
        String zsffdm;
        BigDecimal hdsre;
        BigDecimal jsje;
        String fsdm;
        String szsmdm;
        Timestamp lrrq;
        BigDecimal hssre;
        String zsffmc;
        String szmc;
        BigDecimal jfzce;
        BigDecimal yjl;
        Timestamp sbrq;
        String szsmmc;
        BigDecimal sl;
        String swjgzzjgdm;
        BigDecimal ynse;
        String jsjdm;
        Timestamp skssjsrq;
        BigDecimal bqybse;
        String nd;
        String qxdm;

        public Wqyys () {}
        public Timestamp getSkssksrq() {
                return skssksrq;
        }
        public String getNsrmc() {
                return nsrmc;
        }
        public String getLrr() {
                return lrr;
        }
        public BigDecimal getHtcje() {
                return htcje;
        }
        public BigDecimal getYinse() {
                return yinse;
        }
        public BigDecimal getSre() {
                return sre;
        }
        public Timestamp getCjrq() {
                return cjrq;
        }
        public String getZsffdm() {
                return zsffdm;
        }
        public BigDecimal getHdsre() {
                return hdsre;
        }
        public BigDecimal getJsje() {
                return jsje;
        }
        public String getFsdm() {
                return fsdm;
        }
        public String getSzsmdm() {
                return szsmdm;
        }
        public Timestamp getLrrq() {
                return lrrq;
        }
        public BigDecimal getHssre() {
                return hssre;
        }
        public String getZsffmc() {
                return zsffmc;
        }
        public String getSzmc() {
                return szmc;
        }
        public BigDecimal getJfzce() {
                return jfzce;
        }
        public BigDecimal getYjl() {
                return yjl;
        }
        public Timestamp getSbrq() {
                return sbrq;
        }
        public String getSzsmmc() {
                return szsmmc;
        }
        public BigDecimal getSl() {
                return sl;
        }
        public String getSwjgzzjgdm() {
                return swjgzzjgdm;
        }
        public BigDecimal getYnse() {
                return ynse;
        }
        public String getJsjdm() {
                return jsjdm;
        }
        public Timestamp getSkssjsrq() {
                return skssjsrq;
        }
        public BigDecimal getBqybse() {
                return bqybse;
        }
        public void setSkssksrq( Timestamp _skssksrq ) {
                skssksrq = _skssksrq;
        }
        public void setNsrmc( String _nsrmc ) {
                nsrmc = _nsrmc;
        }
        public void setLrr( String _lrr ) {
                lrr = _lrr;
        }
        public void setHtcje( BigDecimal _htcje ) {
                htcje = _htcje ;
        }
        public void setYinse( BigDecimal _yinse ) {
                yinse = _yinse ;
        }
        public void setSre( BigDecimal _sre ) {
                sre = _sre ;
        }
        public void setCjrq( Timestamp _cjrq ) {
                cjrq = _cjrq;
        }
        public void setZsffdm( String _zsffdm ) {
                zsffdm = _zsffdm;
        }
        public void setHdsre( BigDecimal _hdsre ) {
                hdsre = _hdsre ;
        }
        public void setJsje( BigDecimal _jsje ) {
                jsje = _jsje ;
        }
        public void setFsdm( String _fsdm ) {
                fsdm = _fsdm;
        }
        public void setSzsmdm( String _szsmdm ) {
                szsmdm = _szsmdm;
        }
        public void setLrrq( Timestamp _lrrq ) {
                lrrq = _lrrq;
        }
        public void setHssre( BigDecimal _hssre ) {
                hssre = _hssre ;
        }
        public void setZsffmc( String _zsffmc ) {
                zsffmc = _zsffmc;
        }
        public void setSzmc( String _szmc ) {
                szmc = _szmc;
        }
        public void setJfzce( BigDecimal _jfzce ) {
                jfzce = _jfzce ;
        }
        public void setYjl( BigDecimal _yjl ) {
                yjl = _yjl ;
        }
        public void setSbrq( Timestamp _sbrq ) {
                sbrq = _sbrq;
        }
        public void setSzsmmc( String _szsmmc ) {
                szsmmc = _szsmmc;
        }
        public void setSl( BigDecimal _sl ) {
                sl = _sl ;
        }
        public void setSwjgzzjgdm( String _swjgzzjgdm ) {
                swjgzzjgdm = _swjgzzjgdm;
        }
        public void setYnse( BigDecimal _ynse ) {
                ynse = _ynse ;
        }
        public void setJsjdm( String _jsjdm ) {
                jsjdm = _jsjdm;
        }
        public void setSkssjsrq( Timestamp _skssjsrq ) {
                skssjsrq = _skssjsrq;
        }
        public void setBqybse( BigDecimal _bqybse ) {
                bqybse = _bqybse ;
        }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }
}
