/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 24-Ò»ÔÂ-2005 15:26:47
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Wynsksb implements ORObject {

	Timestamp lrrq;
	String qxdm;
	String sjly;
	Timestamp skssksrq;
	String jsjdm;
	String nd;
	String zsswjgzzjgdm;
	Timestamp skssjsrq;
	String swjgzzjgdm;
	String bz;
	Timestamp cjrq;
	String sbbh;
	Timestamp sbrq;
	String fsdm;
	String lrr;
	String wssbyydm;
	String wssbyynr;
	String lrrmc;
	public Wynsksb () {}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getQxdm() {
		return qxdm;
	}
	public String getSjly() {
		return sjly;
	}
	public Timestamp getSkssksrq() {
		return skssksrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getNd() {
		return nd;
	}
	public String getZsswjgzzjgdm() {
		return zsswjgzzjgdm;
	}
	public Timestamp getSkssjsrq() {
		return skssjsrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public String getBz() {
		return bz;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getSbbh() {
		return sbbh;
	}
	public Timestamp getSbrq() {
		return sbrq;
	}
	public String getFsdm() {
		return fsdm;
	}
	public String getLrr() {
		return lrr;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public void setSjly( String _sjly ) {
		sjly = _sjly;
	}
	public void setSkssksrq( Timestamp _skssksrq ) {
		skssksrq = _skssksrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setZsswjgzzjgdm( String _zsswjgzzjgdm ) {
		zsswjgzzjgdm = _zsswjgzzjgdm;
	}
	public void setSkssjsrq( Timestamp _skssjsrq ) {
		skssjsrq = _skssjsrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSbbh( String _sbbh ) {
		sbbh = _sbbh;
	}
	public void setSbrq( Timestamp _sbrq ) {
		sbrq = _sbrq;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public String getWssbyydm() {
		return wssbyydm;
	}
	public void setWssbyydm(String wssbyydm) {
		this.wssbyydm = wssbyydm;
	}
	public String getWssbyynr() {
		return wssbyynr;
	}
	public void setWssbyynr(String wssbyynr) {
		this.wssbyynr = wssbyynr;
	}
	public String getLrrmc() {
		return lrrmc;
	}
	public void setLrrmc(String lrrmc) {
		this.lrrmc = lrrmc;
	}

}
