/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 24-Ò»ÔÂ-2005 15:26:11
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Wynskszsm implements ORObject {

	String zxbs;
	String szsmdm;
	String bz;
	String ztbs;
	public Wynskszsm () {}
	public String getZxbs() {
		return zxbs;
	}
	public String getSzsmdm() {
		return szsmdm;
	}
	public String getBz() {
		return bz;
	}
	public String getZtbs() {
		return ztbs;
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setSzsmdm( String _szsmdm ) {
		szsmdm = _szsmdm;
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setZtbs( String _ztbs ) {
		ztbs = _ztbs;
	}

}
