/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 07-Ê®ÔÂ-2003 20:01:03
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Yh implements ORObject {

	String lrr;
	Timestamp zhgxsj;
	String yhdm;
	String zxbs;
	Timestamp lrrq;
	String lwzt;
	String yhmc;
	public Yh () {}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getZhgxsj() {
		return zhgxsj;
	}
	public String getYhdm() {
		return yhdm;
	}
	public String getZxbs() {
		return zxbs;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getLwzt() {
		return lwzt;
	}
	public String getYhmc() {
		return yhmc;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setZhgxsj( Timestamp _zhgxsj ) {
		zhgxsj = _zhgxsj;
	}
	public void setYhdm( String _yhdm ) {
		yhdm = _yhdm;
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setLwzt( String _lwzt ) {
		lwzt = _lwzt;
	}
	public void setYhmc( String _yhmc ) {
		yhmc = _yhmc;
	}

}
