/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 07-Ò»ÔÂ-2005 16:01:25
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Yhkkhzxx implements ORObject {

	String bcgyydm;
	String jkpzh;
	String nd;
	String zh;
	String lrr;
	String scjxdm;
	String jsjdm;
	Timestamp kkrq;
	String ysjcdm;
	String kkbz;
	double sjje;
	String nsrmc;
	Timestamp skssksrq;
	String gjbzhydm;
	String ysjcmc;
	String kkdwdm;
	String yd;
	String jydzlxdm;
	String yskmdm;
	String swjgzzjgdm;
	double sjfc;
	String djzclxdm;
	double sjrd;
	String swjgzzjgmc;
	String qxdm;
	String gkzzjgdm;
	Timestamp lrrq;
	String cjr;
	double rkje;
	String szsmdm;
	double qjfc;
	String yhdm;
	String lsgxdm;
	String gkzzjgmc;
	String szsmmc;
	Timestamp skssjsrq;
	Timestamp cjrq;
	public Yhkkhzxx () {}
	public String getBcgyydm() {
		return bcgyydm;
	}
	public String getJkpzh() {
		return jkpzh;
	}
	public String getNd() {
		return nd;
	}
	public String getZh() {
		return zh;
	}
	public String getLrr() {
		return lrr;
	}
	public String getScjxdm() {
		return scjxdm;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public Timestamp getKkrq() {
		return kkrq;
	}
	public String getYsjcdm() {
		return ysjcdm;
	}
	public String getKkbz() {
		return kkbz;
	}
	public double getSjje() {
		return sjje;
	}
	public String getNsrmc() {
		return nsrmc;
	}
	public Timestamp getSkssksrq() {
		return skssksrq;
	}
	public String getGjbzhydm() {
		return gjbzhydm;
	}
	public String getYsjcmc() {
		return ysjcmc;
	}
	public String getKkdwdm() {
		return kkdwdm;
	}
	public String getYd() {
		return yd;
	}
	public String getJydzlxdm() {
		return jydzlxdm;
	}
	public String getYskmdm() {
		return yskmdm;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public double getSjfc() {
		return sjfc;
	}
	public String getDjzclxdm() {
		return djzclxdm;
	}
	public double getSjrd() {
		return sjrd;
	}
	public String getSwjgzzjgmc() {
		return swjgzzjgmc;
	}
	public String getQxdm() {
		return qxdm;
	}
	public String getGkzzjgdm() {
		return gkzzjgdm;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getCjr() {
		return cjr;
	}
	public double getRkje() {
		return rkje;
	}
	public String getSzsmdm() {
		return szsmdm;
	}
	public double getQjfc() {
		return qjfc;
	}
	public String getYhdm() {
		return yhdm;
	}
	public String getLsgxdm() {
		return lsgxdm;
	}
	public String getGkzzjgmc() {
		return gkzzjgmc;
	}
	public String getSzsmmc() {
		return szsmmc;
	}
	public Timestamp getSkssjsrq() {
		return skssjsrq;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public void setBcgyydm( String _bcgyydm ) {
		bcgyydm = _bcgyydm;
	}
	public void setJkpzh( String _jkpzh ) {
		jkpzh = _jkpzh;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setZh( String _zh ) {
		zh = _zh;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setScjxdm( String _scjxdm ) {
		scjxdm = _scjxdm;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setKkrq( Timestamp _kkrq ) {
		kkrq = _kkrq;
	}
	public void setYsjcdm( String _ysjcdm ) {
		ysjcdm = _ysjcdm;
	}
	public void setKkbz( String _kkbz ) {
		kkbz = _kkbz;
	}
	public void setSjje( double _sjje ) {
		sjje = _sjje;
	}
	public void setSjje( BigDecimal _sjje ) {
		sjje = _sjje.doubleValue();
	}
	public void setNsrmc( String _nsrmc ) {
		nsrmc = _nsrmc;
	}
	public void setSkssksrq( Timestamp _skssksrq ) {
		skssksrq = _skssksrq;
	}
	public void setGjbzhydm( String _gjbzhydm ) {
		gjbzhydm = _gjbzhydm;
	}
	public void setYsjcmc( String _ysjcmc ) {
		ysjcmc = _ysjcmc;
	}
	public void setKkdwdm( String _kkdwdm ) {
		kkdwdm = _kkdwdm;
	}
	public void setYd( String _yd ) {
		yd = _yd;
	}
	public void setJydzlxdm( String _jydzlxdm ) {
		jydzlxdm = _jydzlxdm;
	}
	public void setYskmdm( String _yskmdm ) {
		yskmdm = _yskmdm;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setSjfc( double _sjfc ) {
		sjfc = _sjfc;
	}
	public void setSjfc( BigDecimal _sjfc ) {
		sjfc = _sjfc.doubleValue();
	}
	public void setDjzclxdm( String _djzclxdm ) {
		djzclxdm = _djzclxdm;
	}
	public void setSjrd( double _sjrd ) {
		sjrd = _sjrd;
	}
	public void setSjrd( BigDecimal _sjrd ) {
		sjrd = _sjrd.doubleValue();
	}
	public void setSwjgzzjgmc( String _swjgzzjgmc ) {
		swjgzzjgmc = _swjgzzjgmc;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public void setGkzzjgdm( String _gkzzjgdm ) {
		gkzzjgdm = _gkzzjgdm;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setRkje( double _rkje ) {
		rkje = _rkje;
	}
	public void setRkje( BigDecimal _rkje ) {
		rkje = _rkje.doubleValue();
	}
	public void setSzsmdm( String _szsmdm ) {
		szsmdm = _szsmdm;
	}
	public void setQjfc( double _qjfc ) {
		qjfc = _qjfc;
	}
	public void setQjfc( BigDecimal _qjfc ) {
		qjfc = _qjfc.doubleValue();
	}
	public void setYhdm( String _yhdm ) {
		yhdm = _yhdm;
	}
	public void setLsgxdm( String _lsgxdm ) {
		lsgxdm = _lsgxdm;
	}
	public void setGkzzjgmc( String _gkzzjgmc ) {
		gkzzjgmc = _gkzzjgmc;
	}
	public void setSzsmmc( String _szsmmc ) {
		szsmmc = _szsmmc;
	}
	public void setSkssjsrq( Timestamp _skssjsrq ) {
		skssjsrq = _skssjsrq;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}

}
