/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:48
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Yhsbgz implements ORObject {

	Timestamp skssksrq;
	String jsjdm;
	String nd;
	BigDecimal hjfs;
	Timestamp skssjsrq;
	String swjgzzjgdm;
	BigDecimal hjynse;
	BigDecimal hjjsje;
	String lrr;
	String fsdm;
    Timestamp sbrq;
    Timestamp cjrq;
    Timestamp lrrq;
    String qxdm;

	public Yhsbgz () {}
	public Timestamp getSkssksrq() {
		return skssksrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getNd() {
		return nd;
	}
	public BigDecimal getHjfs() {
		return hjfs;
	}
	public Timestamp getSkssjsrq() {
		return skssjsrq;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public BigDecimal getHjynse() {
		return hjynse;
	}
	public BigDecimal getHjjsje() {
		return hjjsje;
	}
	public String getLrr() {
		return lrr;
	}
	public String getFsdm() {
		return fsdm;
	}
	public void setSkssksrq( Timestamp _skssksrq ) {
		skssksrq = _skssksrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setHjfs( BigDecimal _hjfs ) {
		hjfs = _hjfs ;
	}
	public void setSkssjsrq( Timestamp _skssjsrq ) {
		skssjsrq = _skssjsrq;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setHjynse( BigDecimal _hjynse ) {
		hjynse = _hjynse ;
	}
	public void setHjjsje( BigDecimal _hjjsje ) {
		hjjsje = _hjjsje ;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setFsdm( String _fsdm ) {
		fsdm = _fsdm;
	}
    public Timestamp getSbrq()
    {
        return sbrq;
    }

    public void setSbrq(Timestamp sbrq)
    {
        this.sbrq = sbrq;
    }
    public Timestamp getCjrq()
    {
        return cjrq;
    }
    public void setCjrq(Timestamp cjrq)
    {
        this.cjrq = cjrq;
    }
    public Timestamp getLrrq()
    {
        return lrrq;
    }
    public void setLrrq(Timestamp lrrq)
    {
        this.lrrq = lrrq;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }
}