/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:46
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Yhsbgmx implements ORObject {

	BigDecimal jsje;
	String szsmmc;
	String jsjdm;
	BigDecimal sl;
	String nd;
	BigDecimal fs;
	String bz;
	BigDecimal sjse;
	String szsmdm;
	String szdm;
    String swjgzzjgdm;
    Timestamp cjrq;
    Timestamp lrrq;
    String qxdm;

	public Yhsbgmx () {}
	public BigDecimal getJsje() {
		return jsje;
	}
	public String getSzsmmc() {
		return szsmmc;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public BigDecimal getSl() {
		return sl;
	}
	public String getNd() {
		return nd;
	}
	public BigDecimal getFs() {
		return fs;
	}
	public String getBz() {
		return bz;
	}
	public BigDecimal getSjse() {
		return sjse;
	}
	public String getSzsmdm() {
		return szsmdm;
	}
	public String getSzdm() {
		return szdm;
	}
	public void setJsje( BigDecimal _jsje ) {
		jsje = _jsje ;
	}
	public void setSzsmmc( String _szsmmc ) {
		szsmmc = _szsmmc;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setSl( BigDecimal _sl ) {
		sl = _sl ;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setFs( BigDecimal _fs ) {
		fs = _fs ;
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setSjse( BigDecimal _sjse ) {
		sjse = _sjse ;
	}
	public void setSzsmdm( String _szsmdm ) {
		szsmdm = _szsmdm;
	}
	public void setSzdm( String _szdm ) {
		szdm = _szdm;
	}
  public String getSwjgzzjgdm() {
    return swjgzzjgdm;
  }
  public void setSwjgzzjgdm(String swjgzzjgdm) {
    this.swjgzzjgdm = swjgzzjgdm;
  }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }
    public Timestamp getLrrq()
    {
        return lrrq;
    }
    public void setLrrq(Timestamp lrrq)
    {
        this.lrrq = lrrq;
    }
    public Timestamp getCjrq()
    {
        return cjrq;
    }
    public void setCjrq(Timestamp cjrq)
    {
        this.cjrq = cjrq;
    }

}
