/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:36:49
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;

import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
 * This is the entity / business object
 * We will use this business object to demonstrate OR Mapping in Kernl can
 * be used for composition.
 **/
public class Yhsgmz implements ORObject
{

    String xspzh;
    String dsjsjdm;
    Timestamp cjrq;
    Timestamp lrrq;
    String dsdwmc;
    String sjly;
    String swjgzzjgdm;
    String fsdm;
    String lrr;
    String jkpzh;
    Timestamp hzrq;
    String yhzbs;
    BigDecimal hjje;
    String hzr;
     String hzfs;
     String nd;
    private String zhdm;
    private String jzbs;
    private String pkjbdh;
    private String qxdm;
    public Yhsgmz()
    {}

    public Timestamp getCjrq()
    {
        return cjrq;
    }

    public String getDsdwmc()
    {
        return dsdwmc;
    }

    public String getDsjsjdm()
    {
        return dsjsjdm;
    }

    public String getFsdm()
    {
        return fsdm;
    }

    public BigDecimal getHjje()
    {
        return hjje;
    }

    public String getHzr()
    {
        return hzr;
    }

    public Timestamp getHzrq()
    {
        return hzrq;
    }

    public String getJkpzh()
    {
        return jkpzh;
    }

    public String getLrr()
    {
        return lrr;
    }

    public Timestamp getLrrq()
    {
        return lrrq;
    }

    public String getSjly()
    {
        return sjly;
    }

    public String getSwjgzzjgdm()
    {
        return swjgzzjgdm;
    }

    public String getXspzh()
    {
        return xspzh;
    }

    public String getYhzbs()
    {
        return yhzbs;
    }

    public void setCjrq(Timestamp cjrq)
    {
        this.cjrq = cjrq;
    }

    public void setDsdwmc(String dsdwmc)
    {
        this.dsdwmc = dsdwmc;
    }

    public void setDsjsjdm(String dsjsjdm)
    {
        this.dsjsjdm = dsjsjdm;
    }

    public void setFsdm(String fsdm)
    {
        this.fsdm = fsdm;
    }

    public void setHjje(BigDecimal hjje)
    {
        this.hjje = hjje;
    }

    public void setHzr(String hzr)
    {
        this.hzr = hzr;
    }

    public void setHzrq(Timestamp hzrq)
    {
        this.hzrq = hzrq;
    }

    public void setJkpzh(String jkpzh)
    {
        this.jkpzh = jkpzh;
    }

    public void setLrr(String lrr)
    {
        this.lrr = lrr;
    }

    public void setLrrq(Timestamp lrrq)
    {
        this.lrrq = lrrq;
    }

    public void setSjly(String sjly)
    {
        this.sjly = sjly;
    }

    public void setSwjgzzjgdm(String swjgzzjgdm)
    {
        this.swjgzzjgdm = swjgzzjgdm;
    }

    public void setXspzh(String xspzh)
    {
        this.xspzh = xspzh;
    }

    public void setYhzbs(String yhzbs)
    {
        this.yhzbs = yhzbs;
    }
    public String getHzfs()
    {
        return hzfs;
    }
    public void setHzfs(String hzfs)
    {
        hzfs = hzfs;
    }
    public String getNd()
    {
        return nd;
    }
    public void setNd(String nd)
    {
        this.nd = nd;
    }
    public String getZhdm()
    {
        return zhdm;
    }
    public void setZhdm(String zhdm)
    {
        this.zhdm = zhdm;
    }
    public String getJzbs()
    {
        return jzbs;
    }
    public void setJzbs(String jzbs)
    {
        this.jzbs = jzbs;
    }
    public String getPkjbdh()
    {
        return pkjbdh;
    }
    public void setPkjbdh(String pkjbdh)
    {
        this.pkjbdh = pkjbdh;
    }
    public String getQxdm()
    {
        return qxdm;
    }
    public void setQxdm(String qxdm)
    {
        this.qxdm = qxdm;
    }
}