/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:35:33
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Yhsspmz implements ORObject {

	String lrr;
	Timestamp lrrq;
	BigDecimal spmzje;
	String spmzdm;
	public Yhsspmz () {}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public BigDecimal getSpmzje() {
		return spmzje;
	}
	public String getSpmzdm() {
		return spmzdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setSpmzje( BigDecimal _spmzje ) {
		spmzje = _spmzje;
	}
	public void setSpmzdm( String _spmzdm ) {
		spmzdm = _spmzdm;
	}

}
