/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 20-Ê®ÔÂ-2003 11:22:46
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Ysjc implements ORObject {

	String lrr;
	String ysjcdm;
	String zxbs;
	Timestamp lrrq;
	String ysjcmc;
	public Ysjc () {}
	public String getLrr() {
		return lrr;
	}
	public String getYsjcdm() {
		return ysjcdm;
	}
	public String getZxbs() {
		return zxbs;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getYsjcmc() {
		return ysjcmc;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setYsjcdm( String _ysjcdm ) {
		ysjcdm = _ysjcdm;
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setYsjcmc( String _ysjcmc ) {
		ysjcmc = _ysjcmc;
	}

}
