/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 20-Ê®ÔÂ-2003 11:22:46
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Yskm implements ORObject {

	Timestamp lrrq;
	double sjfcbl;
	String zxbs;
	String mrszsmdm;
	double qxfcbl;
	String yskmdm;
	String nd;
	String ysjcdm;
	Timestamp sxrq;
	String yskmmc;
	String lrr;
	double zyfcbl;
	public Yskm () {}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public double getSjfcbl() {
		return sjfcbl;
	}
	public String getZxbs() {
		return zxbs;
	}
	public String getMrszsmdm() {
		return mrszsmdm;
	}
	public double getQxfcbl() {
		return qxfcbl;
	}
	public String getYskmdm() {
		return yskmdm;
	}
	public String getNd() {
		return nd;
	}
	public String getYsjcdm() {
		return ysjcdm;
	}
	public Timestamp getSxrq() {
		return sxrq;
	}
	public String getYskmmc() {
		return yskmmc;
	}
	public String getLrr() {
		return lrr;
	}
	public double getZyfcbl() {
		return zyfcbl;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setSjfcbl( double _sjfcbl ) {
		sjfcbl = _sjfcbl;
	}
	public void setSjfcbl( BigDecimal _sjfcbl ) {
		sjfcbl = _sjfcbl.doubleValue();
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setMrszsmdm( String _mrszsmdm ) {
		mrszsmdm = _mrszsmdm;
	}
	public void setQxfcbl( double _qxfcbl ) {
		qxfcbl = _qxfcbl;
	}
	public void setQxfcbl( BigDecimal _qxfcbl ) {
		qxfcbl = _qxfcbl.doubleValue();
	}
	public void setYskmdm( String _yskmdm ) {
		yskmdm = _yskmdm;
	}
	public void setNd( String _nd ) {
		nd = _nd;
	}
	public void setYsjcdm( String _ysjcdm ) {
		ysjcdm = _ysjcdm;
	}
	public void setSxrq( Timestamp _sxrq ) {
		sxrq = _sxrq;
	}
	public void setYskmmc( String _yskmmc ) {
		yskmmc = _yskmmc;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setZyfcbl( double _zyfcbl ) {
		zyfcbl = _zyfcbl;
	}
	public void setZyfcbl( BigDecimal _zyfcbl ) {
		zyfcbl = _zyfcbl.doubleValue();
	}

}
