/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 03-¾ÅÔÂ-2003 14:53:51
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Zjlx implements ORObject {

	String zjlxdm;
	String lrr;
	Timestamp zhgxsj;
	String zxbs;
	Timestamp lrrq;
	String zjlxmc;
	public Zjlx () {}
	public String getZjlxdm() {
		return zjlxdm;
	}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getZhgxsj() {
		return zhgxsj;
	}
	public String getZxbs() {
		return zxbs;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getZjlxmc() {
		return zjlxmc;
	}
	public void setZjlxdm( String _zjlxdm ) {
		zjlxdm = _zjlxdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setZhgxsj( Timestamp _zhgxsj ) {
		zhgxsj = _zhgxsj;
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setZjlxmc( String _zjlxmc ) {
		zjlxmc = _zjlxmc;
	}

}
