/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 10-¾ÅÔÂ-2003 16:35:35
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Zqlx implements ORObject {

	String lrr;
	BigDecimal zqksrq;
	BigDecimal zqts;
	BigDecimal skssq;
	String zqlxmc;
	Timestamp lrrq;
	String zqzq;
	String zqlxdm;
        Timestamp tyrq;
    private String jglxdm;
	public Zqlx () {}
	public String getLrr() {
		return lrr;
	}
	public BigDecimal getZqksrq() {
		return zqksrq;
	}
	public BigDecimal getZqts() {
		return zqts;
	}
	public BigDecimal getSkssq() {
		return skssq;
	}
	public String getZqlxmc() {
		return zqlxmc;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getZqzq() {
		return zqzq;
	}
	public String getZqlxdm() {
		return zqlxdm;
	}

        public Timestamp getTyrq()
        {
            return tyrq;
        }

	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setZqksrq( BigDecimal _zqksrq ) {
		zqksrq = _zqksrq;
	}
	public void setZqts( BigDecimal _zqts ) {
		zqts = _zqts;
	}
	public void setSkssq( BigDecimal _skssq ) {
		skssq = _skssq;
	}
	public void setZqlxmc( String _zqlxmc ) {
		zqlxmc = _zqlxmc;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setZqzq( String _zqzq ) {
		zqzq = _zqzq;
	}
	public void setZqlxdm( String _zqlxdm ) {
		zqlxdm = _zqlxdm;
	}

        public void setTyrq(Timestamp _tyrq)
        {
            tyrq = _tyrq;
        }
    public String getJglxdm()
    {
        return jglxdm;
    }
    public void setJglxdm(String jglxdm)
    {
        this.jglxdm = jglxdm;
    }

}
