/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 17-Ê®Ò»ÔÂ-2003 21:14:36
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;

import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
 * This is the entity / business object
 * We will use this business object to demonstrate OR Mapping in Kernl can
 * be used for composition.
 **/
public class Zrrgrsdsz implements ORObject
{
    String sbbh;
    Timestamp skssksrq;
    String txdz;
    BigDecimal dwfdbl;
    Timestamp cjrq;
    String cjr;
    String fwdw;
    String yzbm;
    Timestamp lrrq;
    String jnzz;
    String zjlxdm;
    String gjdm;
    Timestamp sbrq;
    Timestamp dhrq;
    String zydm;
    String dh;
    String jsjdm;
    Timestamp skssjsrq;
    String zjhm;
    String fwdd;
    String qxdm;
    private String swjgzzjgdm;
    public Zrrgrsdsz()
    {}

    public Timestamp getSkssksrq()
    {
        return skssksrq;
    }

    public String getTxdz()
    {
        return txdz;
    }

    public BigDecimal getDwfdbl()
    {
        return dwfdbl;
    }

    public Timestamp getCjrq()
    {
        return cjrq;
    }

    public String getCjr()
    {
        return cjr;
    }

    public String getFwdw()
    {
        return fwdw;
    }

    public String getYzbm()
    {
        return yzbm;
    }

    public Timestamp getLrrq()
    {
        return lrrq;
    }

    public String getJnzz()
    {
        return jnzz;
    }

    public String getZjlxdm()
    {
        return zjlxdm;
    }

    public String getGjdm()
    {
        return gjdm;
    }

    public Timestamp getSbrq()
    {
        return sbrq;
    }

    public Timestamp getDhrq()
    {
        return dhrq;
    }

    public String getZydm()
    {
        return zydm;
    }

    public String getDh()
    {
        return dh;
    }

    public String getJsjdm()
    {
        return jsjdm;
    }

    public Timestamp getSkssjsrq()
    {
        return skssjsrq;
    }

    public String getZjhm()
    {
        return zjhm;
    }

    public String getFwdd()
    {
        return fwdd;
    }

    public String getQxdm()
    {
        return qxdm;
    }

    public void setSkssksrq(Timestamp _skssksrq)
    {
        skssksrq = _skssksrq;
    }

    public void setTxdz(String _txdz)
    {
        txdz = _txdz;
    }

    public void setDwfdbl(BigDecimal _dwfdbl)
    {
        dwfdbl = _dwfdbl;
    }

    public void setCjrq(Timestamp _cjrq)
    {
        cjrq = _cjrq;
    }

    public void setCjr(String _cjr)
    {
        cjr = _cjr;
    }

    public void setFwdw(String _fwdw)
    {
        fwdw = _fwdw;
    }

    public void setYzbm(String _yzbm)
    {
        yzbm = _yzbm;
    }

    public void setLrrq(Timestamp _lrrq)
    {
        lrrq = _lrrq;
    }

    public void setJnzz(String _jnzz)
    {
        jnzz = _jnzz;
    }

    public void setZjlxdm(String _zjlxdm)
    {
        zjlxdm = _zjlxdm;
    }

    public void setGjdm(String _gjdm)
    {
        gjdm = _gjdm;
    }

    public void setSbrq(Timestamp _sbrq)
    {
        sbrq = _sbrq;
    }

    public void setDhrq(Timestamp _dhrq)
    {
        dhrq = _dhrq;
    }

    public void setZydm(String _zydm)
    {
        zydm = _zydm;
    }

    public void setDh(String _dh)
    {
        dh = _dh;
    }

    public void setJsjdm(String _jsjdm)
    {
        jsjdm = _jsjdm;
    }

    public void setSkssjsrq(Timestamp _skssjsrq)
    {
        skssjsrq = _skssjsrq;
    }

    public void setZjhm(String _zjhm)
    {
        zjhm = _zjhm;
    }

    public void setFwdd(String _fwdd)
    {
        fwdd = _fwdd;
    }

    public void setQxdm(String _qxdm)
    {
        qxdm = _qxdm;
    }

    public String getSwjgzzjgdm()
    {
        return swjgzzjgdm;
    }

    public void setSwjgzzjgdm(String swjgzzjgdm)
    {
        this.swjgzzjgdm = swjgzzjgdm;
    }

    public String getSbbh()
    {
        return sbbh;
    }

    public void setSbbh(String sbbh)
    {
        this.sbbh = sbbh;
    }

}