/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 17-Ê®Ò»ÔÂ-2003 21:08:01
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;

import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
 * This is the entity / business object
 * We will use this business object to demonstrate OR Mapping in Kernl can
 * be used for composition.
 **/
public class Zrrgrsdsmx implements ORObject
{
    String sbbh;
    BigDecimal whpj;
    BigDecimal ykjse;
    BigDecimal jfye;
    BigDecimal ybtsk;
    BigDecimal yjzgsk;
    BigDecimal ynssde;
    BigDecimal sskcs;
    String szsmdm;
    Timestamp lrrq;
    BigDecimal fdkce;
    BigDecimal srermb;
    Timestamp sdjsrq;
    Timestamp sbrq;
    Timestamp cjrq;
    Timestamp sdksrq;
    String sdksrqStr;
    String sdjsrqStr;
    String bzdm;
    BigDecimal sl;
    BigDecimal zhrmb;
    BigDecimal ynse;
    String jsjdm;
    BigDecimal rmbhj;
    BigDecimal je;
    String qxdm;
    String swjgzzjgdm;
    String jeStr;
    String zhStr;
    String bzdmStr;
    String whpjStr;

    public Zrrgrsdsmx()
    {}

    public BigDecimal getWhpj()
    {
        return whpj;
    }

    public BigDecimal getYkjse()
    {
        return ykjse;
    }

    public BigDecimal getJfye()
    {
        return jfye;
    }

    public BigDecimal getYbtsk()
    {
        return ybtsk;
    }

    public BigDecimal getYnssde()
    {
        return ynssde;
    }

    public BigDecimal getSskcs()
    {
        return sskcs;
    }

    public String getSzsmdm()
    {
        return szsmdm;
    }

    public Timestamp getLrrq()
    {
        return lrrq;
    }

    public BigDecimal getSrermb()
    {
        return srermb;
    }

    public Timestamp getSdjsrq()
    {
        return sdjsrq;
    }

    public Timestamp getSbrq()
    {
        return sbrq;
    }

    public Timestamp getCjrq()
    {
        return cjrq;
    }

    public Timestamp getSdksrq()
    {
        return sdksrq;
    }

    public String getBzdm()
    {
        return bzdm;
    }

    public BigDecimal getZhrmb()
    {
        return zhrmb;
    }

    public BigDecimal getSl()
    {
        return sl;
    }

    public BigDecimal getYnse()
    {
        return ynse;
    }

    public String getJsjdm()
    {
        return jsjdm;
    }

    public BigDecimal getRmbhj()
    {
        return rmbhj;
    }

    public BigDecimal getJe()
    {
        return je;
    }

    public String getQxdm()
    {
        return qxdm;
    }

    public void setWhpj(BigDecimal _whpj)
    {
        whpj = _whpj;
    }

    public void setYkjse(BigDecimal _ykjse)
    {
        ykjse = _ykjse;
    }

    public void setJfye(BigDecimal _jfye)
    {
        jfye = _jfye;
    }

    public void setYbtsk(BigDecimal _ybtsk)
    {
        ybtsk = _ybtsk;
    }

    public void setYnssde(BigDecimal _ynssde)
    {
        ynssde = _ynssde;
    }

    public void setSskcs(BigDecimal _sskcs)
    {
        sskcs = _sskcs;
    }

    public void setSzsmdm(String _szsmdm)
    {
        szsmdm = _szsmdm;
    }

    public void setLrrq(Timestamp _lrrq)
    {
        lrrq = _lrrq;
    }

    public void setSrermb(BigDecimal _srermb)
    {
        srermb = _srermb;
    }

    public void setSdjsrq(Timestamp _sdjsrq)
    {
        sdjsrq = _sdjsrq;
    }

    public void setSbrq(Timestamp _sbrq)
    {
        sbrq = _sbrq;
    }

    public void setCjrq(Timestamp _cjrq)
    {
        cjrq = _cjrq;
    }

    public void setSdksrq(Timestamp _sdksrq)
    {
        sdksrq = _sdksrq;
    }

    public void setBzdm(String _bzdm)
    {
        bzdm = _bzdm;
    }

    public void setZhrmb(BigDecimal _zhrmb)
    {
        zhrmb = _zhrmb;
    }

    public void setSl(BigDecimal _sl)
    {
        sl = _sl;
    }

    public void setYnse(BigDecimal _ynse)
    {
        ynse = _ynse;
    }

    public void setJsjdm(String _jsjdm)
    {
        jsjdm = _jsjdm;
    }

    public void setRmbhj(BigDecimal _rmbhj)
    {
        rmbhj = _rmbhj;
    }

    public void setJe(BigDecimal _je)
    {
        je = _je;
    }

    public void setQxdm(String _qxdm)
    {
        qxdm = _qxdm;
    }

    public BigDecimal getFdkce()
    {
        return fdkce;
    }

    public void setFdkce(BigDecimal _fdkce)
    {
        fdkce = _fdkce;
    }

    public BigDecimal getYjzgsk()
    {
        return yjzgsk;
    }

    public void setYjzgsk(BigDecimal _yjzgsk)
    {
        yjzgsk = _yjzgsk;
    }

    public String getSwjgzzjgdm()
    {
        return swjgzzjgdm;
    }

    public void setSwjgzzjgdm(String swjgzzjgdm)
    {
        this.swjgzzjgdm = swjgzzjgdm;
    }

    public String getJeStr()
    {
        return jeStr;
    }

    public void setJeStr(String jeStr)
    {
        this.jeStr = jeStr;
    }

    public String getZhStr()
    {
        return zhStr;
    }

    public void setZhStr(String zhStr)
    {
        this.zhStr = zhStr;
    }

    public String getSdjsrqStr()
    {
        return sdjsrqStr;
    }

    public void setSdjsrqStr(String sdjsrqStr)
    {
        this.sdjsrqStr = sdjsrqStr;
    }

    public String getSdksrqStr()
    {
        return sdksrqStr;
    }

    public void setSdksrqStr(String sdksrqStr)
    {
        this.sdksrqStr = sdksrqStr;
    }

    public String getSbbh()
    {
        return sbbh;
    }

    public void setSbbh(String sbbh)
    {
        this.sbbh = sbbh;
    }
    public String getBzdmStr()
    {
        return bzdmStr;
    }
    public void setBzdmStr(String bzdmStr)
    {
        this.bzdmStr = bzdmStr;
    }
    public String getWhpjStr()
    {
        return whpjStr;
    }
    public void setWhpjStr(String whpjStr)
    {
        this.whpjStr = whpjStr;
    }
}