/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 03-¾ÅÔÂ-2003 14:50:52
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class Zy implements ORObject {

	String lrr;
	Timestamp zhgxsj;
	String zxbs;
	String zymc;
	Timestamp lrrq;
	String zydm;
	public Zy () {}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getZhgxsj() {
		return zhgxsj;
	}
	public String getZxbs() {
		return zxbs;
	}
	public String getZymc() {
		return zymc;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getZydm() {
		return zydm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setZhgxsj( Timestamp _zhgxsj ) {
		zhgxsj = _zhgxsj;
	}
	public void setZxbs( String _zxbs ) {
		zxbs = _zxbs;
	}
	public void setZymc( String _zymc ) {
		zymc = _zymc;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setZydm( String _zydm ) {
		zydm = _zydm;
	}

}
