/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-°ËÔÂ-2006 13:07:56
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class ZYFWJBXX implements ORObject {

	String lrr;
	Timestamp jmsqxz;
	Timestamp fhrq;
	String fwzl;
	Timestamp jmsqxq;
	String cqzsh;
	String sfdj;
	String jmsyzbgyy;
	double qzysyz;
	String fhr;
	String cjr;
	double fcyz;
	Timestamp lrrq;
	double qzmsyz;
	String id;
	String fhbs;
	String djbh;
	double nynse;
	String bz;
	Timestamp cjrq;
	double swjggz;
	String swjgzzjgdm;
	String jmzcdm;
	Timestamp tbrq;
	String jsjdm;
	String qxdm;
	public ZYFWJBXX () {}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getJmsqxz() {
		return jmsqxz;
	}
	public Timestamp getFhrq() {
		return fhrq;
	}
	public String getFwzl() {
		return fwzl;
	}
	public Timestamp getJmsqxq() {
		return jmsqxq;
	}
	public String getCqzsh() {
		return cqzsh;
	}
	public String getSfdj() {
		return sfdj;
	}
	public String getJmsyzbgyy() {
		return jmsyzbgyy;
	}
	public double getQzysyz() {
		return qzysyz;
	}
	public String getFhr() {
		return fhr;
	}
	public String getCjr() {
		return cjr;
	}
	public double getFcyz() {
		return fcyz;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public double getQzmsyz() {
		return qzmsyz;
	}
	public String getId() {
		return id;
	}
	public String getFhbs() {
		return fhbs;
	}
	public String getDjbh() {
		return djbh;
	}
	public double getNynse() {
		return nynse;
	}
	public String getBz() {
		return bz;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public double getSwjggz() {
		return swjggz;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public String getJmzcdm() {
		return jmzcdm;
	}
	public Timestamp getTbrq() {
		return tbrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getQxdm() {
		return qxdm;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setJmsqxz( Timestamp _jmsqxz ) {
		jmsqxz = _jmsqxz;
	}
	public void setFhrq( Timestamp _fhrq ) {
		fhrq = _fhrq;
	}
	public void setFwzl( String _fwzl ) {
		fwzl = _fwzl;
	}
	public void setJmsqxq( Timestamp _jmsqxq ) {
		jmsqxq = _jmsqxq;
	}
	public void setCqzsh( String _cqzsh ) {
		cqzsh = _cqzsh;
	}
	public void setSfdj( String _sfdj ) {
		sfdj = _sfdj;
	}
	public void setJmsyzbgyy( String _jmsyzbgyy ) {
		jmsyzbgyy = _jmsyzbgyy;
	}
	public void setQzysyz( double _qzysyz ) {
		qzysyz = _qzysyz;
	}
	public void setQzysyz( BigDecimal _qzysyz ) {
		qzysyz = _qzysyz.doubleValue();
	}
	public void setFhr( String _fhr ) {
		fhr = _fhr;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setFcyz( double _fcyz ) {
		fcyz = _fcyz;
	}
	public void setFcyz( BigDecimal _fcyz ) {
		fcyz = _fcyz.doubleValue();
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setQzmsyz( double _qzmsyz ) {
		qzmsyz = _qzmsyz;
	}
	public void setQzmsyz( BigDecimal _qzmsyz ) {
		qzmsyz = _qzmsyz.doubleValue();
	}
	public void setId( String _id ) {
		id = _id;
	}
	public void setFhbs( String _fhbs ) {
		fhbs = _fhbs;
	}
	public void setDjbh( String _djbh ) {
		djbh = _djbh;
	}
	public void setNynse( double _nynse ) {
		nynse = _nynse;
	}
	public void setNynse( BigDecimal _nynse ) {
		nynse = _nynse.doubleValue();
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setSwjggz( double _swjggz ) {
		swjggz = _swjggz;
	}
	public void setSwjggz( BigDecimal _swjggz ) {
		swjggz = _swjggz.doubleValue();
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setJmzcdm( String _jmzcdm ) {
		jmzcdm = _jmzcdm;
	}
	public void setTbrq( Timestamp _tbrq ) {
		tbrq = _tbrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}

}
