/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-°ËÔÂ-2006 13:07:56
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class ZYFWBGXX implements ORObject {

	String fhr;
	String bghfwzl;
	String lrr;
	double bgqfcyz;
	String bgqsfdj;
	String bgqbz;
	String jsjdm;
	String bghcqzsh;
	String bghbz;
	Timestamp fhrq;
	double bgqnynse;
	String swjgzzjgdm;
	double bghswjggz;
	Timestamp jmsqxz;
	double bghfcyz;
	String bghsfdj;
	double bgqswjggz;
	double bghqzysyz;
	String jmsyzbgyy;
	String bgqfwzl;
	double bgqqzysyz;
	String fhbs;
	Timestamp jmsqxq;
	double bghqzmsyz;
	String id;
	double bgqqzmsyz;
	String djbh;
	String qxdm;
	String jmzcdm;
	Timestamp lrrq;
	String cjr;
	String bgqcqzsh;
	String bglx;
	double bghnynse;
	Timestamp tbrq;
	String ysfcyzbgyy;
	String jcbh;
	Timestamp cjrq;
	public ZYFWBGXX () {}
	public String getFhr() {
		return fhr;
	}
	public String getBghfwzl() {
		return bghfwzl;
	}
	public String getLrr() {
		return lrr;
	}
	public double getBgqfcyz() {
		return bgqfcyz;
	}
	public String getBgqsfdj() {
		return bgqsfdj;
	}
	public String getBgqbz() {
		return bgqbz;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getBghcqzsh() {
		return bghcqzsh;
	}
	public String getBghbz() {
		return bghbz;
	}
	public Timestamp getFhrq() {
		return fhrq;
	}
	public double getBgqnynse() {
		return bgqnynse;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public double getBghswjggz() {
		return bghswjggz;
	}
	public Timestamp getJmsqxz() {
		return jmsqxz;
	}
	public double getBghfcyz() {
		return bghfcyz;
	}
	public String getBghsfdj() {
		return bghsfdj;
	}
	public double getBgqswjggz() {
		return bgqswjggz;
	}
	public double getBghqzysyz() {
		return bghqzysyz;
	}
	public String getJmsyzbgyy() {
		return jmsyzbgyy;
	}
	public String getBgqfwzl() {
		return bgqfwzl;
	}
	public double getBgqqzysyz() {
		return bgqqzysyz;
	}
	public String getFhbs() {
		return fhbs;
	}
	public Timestamp getJmsqxq() {
		return jmsqxq;
	}
	public double getBghqzmsyz() {
		return bghqzmsyz;
	}
	public String getId() {
		return id;
	}
	public double getBgqqzmsyz() {
		return bgqqzmsyz;
	}
	public String getDjbh() {
		return djbh;
	}
	public String getQxdm() {
		return qxdm;
	}
	public String getJmzcdm() {
		return jmzcdm;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getCjr() {
		return cjr;
	}
	public String getBgqcqzsh() {
		return bgqcqzsh;
	}
	public String getBglx() {
		return bglx;
	}
	public double getBghnynse() {
		return bghnynse;
	}
	public Timestamp getTbrq() {
		return tbrq;
	}
	public String getYsfcyzbgyy() {
		return ysfcyzbgyy;
	}
	public String getJcbh() {
		return jcbh;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public void setFhr( String _fhr ) {
		fhr = _fhr;
	}
	public void setBghfwzl( String _bghfwzl ) {
		bghfwzl = _bghfwzl;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setBgqfcyz( double _bgqfcyz ) {
		bgqfcyz = _bgqfcyz;
	}
	public void setBgqfcyz( BigDecimal _bgqfcyz ) {
		bgqfcyz = _bgqfcyz.doubleValue();
	}
	public void setBgqsfdj( String _bgqsfdj ) {
		bgqsfdj = _bgqsfdj;
	}
	public void setBgqbz( String _bgqbz ) {
		bgqbz = _bgqbz;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setBghcqzsh( String _bghcqzsh ) {
		bghcqzsh = _bghcqzsh;
	}
	public void setBghbz( String _bghbz ) {
		bghbz = _bghbz;
	}
	public void setFhrq( Timestamp _fhrq ) {
		fhrq = _fhrq;
	}
	public void setBgqnynse( double _bgqnynse ) {
		bgqnynse = _bgqnynse;
	}
	public void setBgqnynse( BigDecimal _bgqnynse ) {
		bgqnynse = _bgqnynse.doubleValue();
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setBghswjggz( double _bghswjggz ) {
		bghswjggz = _bghswjggz;
	}
	public void setBghswjggz( BigDecimal _bghswjggz ) {
		bghswjggz = _bghswjggz.doubleValue();
	}
	public void setJmsqxz( Timestamp _jmsqxz ) {
		jmsqxz = _jmsqxz;
	}
	public void setBghfcyz( double _bghfcyz ) {
		bghfcyz = _bghfcyz;
	}
	public void setBghfcyz( BigDecimal _bghfcyz ) {
		bghfcyz = _bghfcyz.doubleValue();
	}
	public void setBghsfdj( String _bghsfdj ) {
		bghsfdj = _bghsfdj;
	}
	public void setBgqswjggz( double _bgqswjggz ) {
		bgqswjggz = _bgqswjggz;
	}
	public void setBgqswjggz( BigDecimal _bgqswjggz ) {
		bgqswjggz = _bgqswjggz.doubleValue();
	}
	public void setBghqzysyz( double _bghqzysyz ) {
		bghqzysyz = _bghqzysyz;
	}
	public void setBghqzysyz( BigDecimal _bghqzysyz ) {
		bghqzysyz = _bghqzysyz.doubleValue();
	}
	public void setJmsyzbgyy( String _jmsyzbgyy ) {
		jmsyzbgyy = _jmsyzbgyy;
	}
	public void setBgqfwzl( String _bgqfwzl ) {
		bgqfwzl = _bgqfwzl;
	}
	public void setBgqqzysyz( double _bgqqzysyz ) {
		bgqqzysyz = _bgqqzysyz;
	}
	public void setBgqqzysyz( BigDecimal _bgqqzysyz ) {
		bgqqzysyz = _bgqqzysyz.doubleValue();
	}
	public void setFhbs( String _fhbs ) {
		fhbs = _fhbs;
	}
	public void setJmsqxq( Timestamp _jmsqxq ) {
		jmsqxq = _jmsqxq;
	}
	public void setBghqzmsyz( double _bghqzmsyz ) {
		bghqzmsyz = _bghqzmsyz;
	}
	public void setBghqzmsyz( BigDecimal _bghqzmsyz ) {
		bghqzmsyz = _bghqzmsyz.doubleValue();
	}
	public void setId( String _id ) {
		id = _id;
	}
	public void setBgqqzmsyz( double _bgqqzmsyz ) {
		bgqqzmsyz = _bgqqzmsyz;
	}
	public void setBgqqzmsyz( BigDecimal _bgqqzmsyz ) {
		bgqqzmsyz = _bgqqzmsyz.doubleValue();
	}
	public void setDjbh( String _djbh ) {
		djbh = _djbh;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public void setJmzcdm( String _jmzcdm ) {
		jmzcdm = _jmzcdm;
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setBgqcqzsh( String _bgqcqzsh ) {
		bgqcqzsh = _bgqcqzsh;
	}
	public void setBglx( String _bglx ) {
		bglx = _bglx;
	}
	public void setBghnynse( double _bghnynse ) {
		bghnynse = _bghnynse;
	}
	public void setBghnynse( BigDecimal _bghnynse ) {
		bghnynse = _bghnynse.doubleValue();
	}
	public void setTbrq( Timestamp _tbrq ) {
		tbrq = _tbrq;
	}
	public void setYsfcyzbgyy( String _ysfcyzbgyy ) {
		ysfcyzbgyy = _ysfcyzbgyy;
	}
	public void setJcbh( String _jcbh ) {
		jcbh = _jcbh;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}

}
