/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 21-°ËÔÂ-2006 13:07:56
 * 
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use 
 * ONLY by licensed users of the product, includes CONFIDENTIAL and 
 * PROPRIETARY information of Beans Factory.  
 *
 */
package com.ttsoft.bjtax.shenbao.model.domain;
import java.sql.*;
import java.util.*;
import java.math.BigDecimal;
import com.ekernel.db.or.ORObject;

/**
* This is the entity / business object
* We will use this business object to demonstrate OR Mapping in Kernl can
* be used for composition.
**/
public class ZYTDJBXX implements ORObject {

	String lrr;
	Timestamp jmsqxz;
	Timestamp fhrq;
	Timestamp jmsqxq;
	String sfdj;
	String sfjnws;
	String jmsyzbgyy;
	String fhr;
	String cjr;
	double tdmj;
	Timestamp lrrq;
	String id;
	double qzysmj;
	String fhbs;
	String djbh;
	double nynse;
	String bz;
	Timestamp cjrq;
	String tdzl;
	String swjgzzjgdm;
	double qzmsmj;
	String jmzcdm;
	String tdzsh;
	Timestamp tbrq;
	String jsjdm;
	String qxdm;
	double mpfmse;
	public ZYTDJBXX () {}
	public String getLrr() {
		return lrr;
	}
	public Timestamp getJmsqxz() {
		return jmsqxz;
	}
	public Timestamp getFhrq() {
		return fhrq;
	}
	public Timestamp getJmsqxq() {
		return jmsqxq;
	}
	public String getSfdj() {
		return sfdj;
	}
	public String getJmsyzbgyy() {
		return jmsyzbgyy;
	}
	public String getFhr() {
		return fhr;
	}
	public String getCjr() {
		return cjr;
	}
	public double getTdmj() {
		return tdmj;
	}
	public Timestamp getLrrq() {
		return lrrq;
	}
	public String getId() {
		return id;
	}
	public double getQzysmj() {
		return qzysmj;
	}
	public String getFhbs() {
		return fhbs;
	}
	public String getDjbh() {
		return djbh;
	}
	public double getNynse() {
		return nynse;
	}
	public String getBz() {
		return bz;
	}
	public Timestamp getCjrq() {
		return cjrq;
	}
	public String getTdzl() {
		return tdzl;
	}
	public String getSwjgzzjgdm() {
		return swjgzzjgdm;
	}
	public double getQzmsmj() {
		return qzmsmj;
	}
	public String getJmzcdm() {
		return jmzcdm;
	}
	public String getTdzsh() {
		return tdzsh;
	}
	public Timestamp getTbrq() {
		return tbrq;
	}
	public String getJsjdm() {
		return jsjdm;
	}
	public String getQxdm() {
		return qxdm;
	}
	public double getMpfmse() {
		return mpfmse;
	}
	public void setLrr( String _lrr ) {
		lrr = _lrr;
	}
	public void setJmsqxz( Timestamp _jmsqxz ) {
		jmsqxz = _jmsqxz;
	}
	public void setFhrq( Timestamp _fhrq ) {
		fhrq = _fhrq;
	}
	public void setJmsqxq( Timestamp _jmsqxq ) {
		jmsqxq = _jmsqxq;
	}
	public void setSfdj( String _sfdj ) {
		sfdj = _sfdj;
	}
	public void setJmsyzbgyy( String _jmsyzbgyy ) {
		jmsyzbgyy = _jmsyzbgyy;
	}
	public void setFhr( String _fhr ) {
		fhr = _fhr;
	}
	public void setCjr( String _cjr ) {
		cjr = _cjr;
	}
	public void setTdmj( double _tdmj ) {
		tdmj = _tdmj;
	}
	public void setTdmj( BigDecimal _tdmj ) {
		tdmj = _tdmj.doubleValue();
	}
	public void setLrrq( Timestamp _lrrq ) {
		lrrq = _lrrq;
	}
	public void setId( String _id ) {
		id = _id;
	}
	public void setQzysmj( double _qzysmj ) {
		qzysmj = _qzysmj;
	}
	public void setQzysmj( BigDecimal _qzysmj ) {
		qzysmj = _qzysmj.doubleValue();
	}
	public void setFhbs( String _fhbs ) {
		fhbs = _fhbs;
	}
	public void setDjbh( String _djbh ) {
		djbh = _djbh;
	}
	public void setNynse( double _nynse ) {
		nynse = _nynse;
	}
	public void setNynse( BigDecimal _nynse ) {
		nynse = _nynse.doubleValue();
	}
	public void setBz( String _bz ) {
		bz = _bz;
	}
	public void setCjrq( Timestamp _cjrq ) {
		cjrq = _cjrq;
	}
	public void setTdzl( String _tdzl ) {
		tdzl = _tdzl;
	}
	public void setSwjgzzjgdm( String _swjgzzjgdm ) {
		swjgzzjgdm = _swjgzzjgdm;
	}
	public void setQzmsmj( double _qzmsmj ) {
		qzmsmj = _qzmsmj;
	}
	public void setQzmsmj( BigDecimal _qzmsmj ) {
		qzmsmj = _qzmsmj.doubleValue();
	}
	public void setJmzcdm( String _jmzcdm ) {
		jmzcdm = _jmzcdm;
	}
	public void setTdzsh( String _tdzsh ) {
		tdzsh = _tdzsh;
	}
	public void setTbrq( Timestamp _tbrq ) {
		tbrq = _tbrq;
	}
	public void setJsjdm( String _jsjdm ) {
		jsjdm = _jsjdm;
	}
	public void setQxdm( String _qxdm ) {
		qxdm = _qxdm;
	}
	public void setMpfmse( double _mpfmse ) {
		mpfmse = _mpfmse;
	}
	public void setMpfmse( BigDecimal _mpfmse ) {
		mpfmse = _mpfmse.doubleValue();
	}
	public String getSfjnws() {
		return sfjnws;
	}
	public void setSfjnws(String sfjnws) {
		this.sfjnws = sfjnws;
	}

}
