/**
 * Copyright (c) Beans factory Pte Ltd. All Rights Reserved.
 * Generated: 09-十二月-2003 20:27:47
 *
 * <p>
 * This SOURCE CODE FILE, which has been generated by Designer for use
 * ONLY by licensed users of the product, includes CONFIDENTIAL and
 * PROPRIETARY information of Beans Factory.
 *
 */
package com.creationstar.bjtax.qsgl.BizLogic.vo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * 申报减免表值对象
 **/
public class Jm implements Serializable {

    String jzbz;
    Timestamp skssksrq;
    BigDecimal jmse;
    String jmxmdm;
    String lrr;
    String ysjcdm;
    String jmlx;
    String nd;
    BigDecimal jsje;
    BigDecimal kssl;
    String fsdm;
    String szsmdm;
    Timestamp lrrq;
    Timestamp sbrq;
    Timestamp cjrq;
    String yskmdm;
    String swjgzzjgdm;
    String jsjdm;
    String djzclxdm;
    Timestamp skssjsrq;
    String qxdm;
    String gjbzhydm;
    public Jm() {}

    public String getJzbz() {
        return jzbz;
    }

    public Timestamp getSkssksrq() {
        return skssksrq;
    }

    public BigDecimal getJmse() {
        return jmse;
    }

    public String getJmxmdm() {
        return jmxmdm;
    }

    public String getLrr() {
        return lrr;
    }

    public String getYsjcdm() {
        return ysjcdm;
    }

    public String getJmlx() {
        return jmlx;
    }

    public String getNd() {
        return nd;
    }

    public BigDecimal getJsje() {
        return jsje;
    }

    public BigDecimal getKssl() {
        return kssl;
    }

    public String getFsdm() {
        return fsdm;
    }

    public String getSzsmdm() {
        return szsmdm;
    }

    public Timestamp getLrrq() {
        return lrrq;
    }

    public Timestamp getSbrq() {
        return sbrq;
    }

    public Timestamp getCjrq() {
        return cjrq;
    }

    public String getYskmdm() {
        return yskmdm;
    }

    public String getSwjgzzjgdm() {
        return swjgzzjgdm;
    }

    public String getJsjdm() {
        return jsjdm;
    }

    public String getDjzclxdm() {
        return djzclxdm;
    }

    public Timestamp getSkssjsrq() {
        return skssjsrq;
    }

    public String getQxdm() {
        return qxdm;
    }

    public String getGjbzhydm() {
        return gjbzhydm;
    }

    public void setJzbz(String _jzbz) {
        jzbz = _jzbz;
    }

    public void setSkssksrq(Timestamp _skssksrq) {
        skssksrq = _skssksrq;
    }

    public void setJmse(BigDecimal _jmse) {
        jmse = _jmse;
    }

    public void setJmxmdm(String _jmxmdm) {
        jmxmdm = _jmxmdm;
    }

    public void setLrr(String _lrr) {
        lrr = _lrr;
    }

    public void setYsjcdm(String _ysjcdm) {
        ysjcdm = _ysjcdm;
    }

    public void setJmlx(String _jmlx) {
        jmlx = _jmlx;
    }

    public void setNd(String _nd) {
        nd = _nd;
    }

    public void setJsje(BigDecimal _jsje) {
        jsje = _jsje;
    }

    public void setKssl(BigDecimal _kssl) {
        kssl = _kssl;
    }

    public void setFsdm(String _fsdm) {
        fsdm = _fsdm;
    }

    public void setSzsmdm(String _szsmdm) {
        szsmdm = _szsmdm;
    }

    public void setLrrq(Timestamp _lrrq) {
        lrrq = _lrrq;
    }

    public void setSbrq(Timestamp _sbrq) {
        sbrq = _sbrq;
    }

    public void setCjrq(Timestamp _cjrq) {
        cjrq = _cjrq;
    }

    public void setYskmdm(String _yskmdm) {
        yskmdm = _yskmdm;
    }

    public void setSwjgzzjgdm(String _swjgzzjgdm) {
        swjgzzjgdm = _swjgzzjgdm;
    }

    public void setJsjdm(String _jsjdm) {
        jsjdm = _jsjdm;
    }

    public void setDjzclxdm(String _djzclxdm) {
        djzclxdm = _djzclxdm;
    }

    public void setSkssjsrq(Timestamp _skssjsrq) {
        skssjsrq = _skssjsrq;
    }

    public void setQxdm(String _qxdm) {
        qxdm = _qxdm;
    }

    public void setGjbzhydm(String _gjbzhydm) {
        gjbzhydm = _gjbzhydm;
    }

}
